### ISSUE TITLE
no css appeared after installation

### ISSUE THREAD

**Issue by macnux** [TypiCMS/Base#10]
i follow all steps menthoied

Create a new project

composer create-project typicms/base mywebsite
Enter the newly created folder

cd mywebsite
DB migration and seed, user creation, npm installation, bower installation and directory rights

php artisan typicms:install
Go to http://mywebsite.local/admin and log in.

installation was successful but 
the page without any css styling and no css found at all !!

**Comment by sdebacker** [comment]
Strange. I just pushed version 2.1.3. Can you reinstall it and check that all is ok ?
