### ISSUE TITLE
Issue with Arcanedev/LogViewer

### ISSUE THREAD

**Issue by InfinityWebMe** [TypiCMS/Base#100]
Salut,

Il me semble que vous parlez français du coup je tente mon post en français (sinon je traduirai ;)).

J'essaye de faire fonctionner typi avec arcanedev/logviewer ( https://github.com/ARCANEDEV/LogViewer ) mais pas moyen d'avoir accès à l'url http://test.dev/log-viewer alors que tout semble correctement configuré et que la route est retourné si je fais un artisan route:list. 
Le système me renvoi à chaque fois l'erreur 404 par défaut de typi.

Auriez vous une idée d'où pourrait provenir le soucis ? 

Merci et bonne soirée,

Yannik

**Comment by sdebacker** [comment]
Bonjour,

En effet je parle français. La raison du dysfonctionnement est certainement que la route appelle le contrôleur du module pages, probablement que si vous mettez le service provider du plugin en question avant les providers de TypiCMS, ça devrait marcher. 

Samuel

**Comment by InfinityWebMe** [comment]
Merci pour la réponse rapide :)

Malheureusement, j'ai déjà fait ce test là, j'ai mis la ligne " Arcanedev\LogViewer\LogViewerServiceProvider::class,", juste après "Vendor Service Providers...".

**Comment by sdebacker** [comment]
J'ai un peu regardé de mon côté mais n'ai pas trouvé de solution. Si de votre côté vous trouvez, ça m'intéresse.

**Comment by InfinityWebMe** [comment]
J'ai réussi a faire afficher le dashboard de la librairie en ajoutant dans app/http/routes.php, la ligne Route::get('log-viewer'); et si je définis manuellement chaque route du plugin, ca fonctionne.

Ce n'est pas encore le nirvana mais ça avance 👍

**Comment by arcanedev-maroc** [comment]
# Description:

The issue with `typicms`: [it has a route that override](https://github.com/TypiCMS/Pages/blob/master/src/Providers/RouteServiceProvider.php#L106) other routes like `log-viewer` routes.

# Solution:

Change the `config/log-viewer.php`:

```php

return [
    // ...

    'route'         => [
        'enabled'    => true,

        'attributes' => [
            'prefix'     => 'admin/log-viewer',

            'middleware' => ['admin'], // To secure the log-viewer
        ],
    ],

    // ...
];

```

Now you can access it `http://your-project.dev/admin/log-viewer`.

**Comment by arcanedev-maroc** [comment]
Je pense que mon package est a de plus flexibilité que `typicms` 😄 

**cc:** @InfinityWebMe @sdebacker

**Comment by InfinityWebMe** [comment]
@arcanedev-maroc  Merci pour votre temps 👍

**Comment by arcanedev-maroc** [comment]
@InfinityWebMe C'est avec plaisir 👍

**Comment by InfinityWebMe** [comment]
@arcanedev-maroc  Je viens de faire le test avec le changement, je rencontre toujours le problème.

Après un route:list, j'ai bien ceci dedans : 
|        | GET|HEAD | admin/log-viewer                             | log-viewer::dashboard     | Arcanedev\LogViewer\Http\Controllers\LogViewerController@index               | admin

Pensez-vous à autre chose ?

**Comment by arcanedev-maroc** [comment]
C'est le seul route de `LogViewer` que tu as sur la liste ?

Il me semble correcte le dashboard route, j'ai ajouté le middleware `admin` pour protégé l’accès (il faut s'authentifié autant qu'admin pour voir les logs sur `admin/log-viewer`).

C'est quoi le type d'erreur que tu reçois ? page 404 ?

**Comment by InfinityWebMe** [comment]
J'ai les autres routes aussi ( admin/log-viewer/logs ,  admin/log-viewer/logs/delete, admin/log-viewer/logs/{date}, admin/log-viewer/logs/{date}/download,  admin/log-viewer/logs/{date}/{level}) mais c'est tout pour log-viewer.

Oui je me suis bien connecté avant et j'ai essayé sans le middleware admin pour être sur. 
Rien dans les logs d'erreur et je tombe sur la page 404.

**Comment by sdebacker** [comment]
Normalement ce problème est réglé avec TypiCMS 3.

**Comment by InfinityWebMe** [comment]
Par curiosité et comme j'utilise toujours typiCMS 2, vous savez me dire ce qui posait problème ?

**Comment by sdebacker** [comment]
C'était l'ordre des routes je pense.
