### ISSUE TITLE
A migrations table was found in database [typicms], no migration and seed were done.

### ISSUE THREAD

**Issue by DanielLagin** [TypiCMS/Base#104]
Hello, I have got an error:
`A migrations table was found in database [typicms], no migration and seed were done.`
when running `php artisan typicms:install`.

Migration creates database named **typicms**, it also creates empty table **typicms_migrations**, but nothing else.

I have tried `composer dump-autoload` before executing installation command.

I use Mysql 5.6.35, php 7.1.1 satisfying all requirements from documentation. 

Thanks a lot.

**Comment by sdebacker** [comment]
You can try to remove the database and rerun php artisan typicms:install.

**Comment by DanielLagin** [comment]
Remove and rerun didnt help.

**Comment by sdebacker** [comment]
I have no other idea why a migration table is found by TypiCMS even when you erased it… you should have a look at laravel configuration files presents in your TypiCMS project.

**Comment by DanielLagin** [comment]
Ok i will try to figure it out.

Is there any other option to get working database? Something like sql dump? Thanks a lot.

**Comment by DanielLagin** [comment]
Ok i came to a solution.

I had to replace `DB_HOST=localhost` with `DB_HOST=127.0.0.1` in .env file.

Then run `composer update` and `php artisan typicms:install`.
