### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by ivarsmednis** [TypiCMS/Base#105]
Hi! I see files marked with v3 with some very exciting updates. The question is - is it stable to use? If so, how would it be possible to install it? Documentation directions lead to 2.9.4 installation. 

Thanks in advance!
i.

**Comment by sdebacker** [comment]
Sure, you can install it with the command `composer create-project typicms/base:dev-master typicmstest`. It's already pretty stable, feel free to open issues for the bugs you found.

**Comment by sdebacker** [comment]
Yes, if you look at the Slides module, you will see an example for a single image.
If you need many galleries for a single page, you can have many sections, each sections can have many images.
If you need many galleries for, say, a News, you will need to develop something custom.

**Comment by ivarsmednis** [comment]
Yes, pages now have another layer of power. For news and generated modules i guess i can use galleries if needed (like in v 2.9) or some kind of global sections that belong to module model instance. Thanks for your input!
