### ISSUE TITLE
V3 Single image problem

### ISSUE THREAD

**Issue by ivarsmednis** [TypiCMS/Base#106]
Tried to install Slides module on fresh TypiCMS and it looks like single image uploads are not working. Please see attached screenshot (note JS error below).

<img width="1287" alt="" src="https://user-images.githubusercontent.com/22047319/32451142-d0625bd8-c31e-11e7-8ca5-1693cfa1489f.png">

**Comment by sdebacker** [comment]
Ok I see, I think you can just run npm run dev and it will be fixed, is it ?

**Comment by ivarsmednis** [comment]
I did run npm run dev and it went without errors, but this error still persists. 
Multiple file uploads (and everything else that i tried so far) are working fine, only this error showing up.

<img width="853" alt="npmrundev" src="https://user-images.githubusercontent.com/22047319/32454606-62977016-c328-11e7-8575-f62d1524eb7c.png">

**Comment by sdebacker** [comment]
It's corrected in Core:3.0.15, running:

```
composer update
php artisan vendor:publish --provider="TypiCMS\Modules\Core\Providers\ModuleProvider"
npm run dev
```

should fix the problem. Is it ?

**Comment by ivarsmednis** [comment]
Yes, the error is gone. thank you!

I tried to add another single image field bgimage, by making field bgimage_id in slides table and adding @include('core::admin._image-fieldset', ['field' => 'bgimage']) in _form.blade.php of slides module. However both image and bgimage fields act the same. I opened _image-fieldset.blade.php and saw that bootform is using dynamic field name. could it be that angular part is hardcoded to use only image field?

**Comment by sdebacker** [comment]
Yes for the moment it's hardcoded, I'm open for a pull request.

**Comment by sdebacker** [comment]
The angular controller are resources/assets/typicms/controllers/ImageController.js and resources/assets/typicms/controllers/DocumentController.js. You can put resources/assets/typicms/controllers/FileController.js to the trash.

**Comment by ivarsmednis** [comment]
Not too familiar with angular,  but controllers don't seem too big. I might take a look later as there  will be a project with need for this at some point. Thanks for directions!
