### ISSUE TITLE
Lier plusieurs fichiers à un model comme pour galleries

### ISSUE THREAD

**Issue by InfinityWebMe** [TypiCMS/Base#108]
Salut,

J'essaye de lier plusieurs fichiers à un modèle comme tu le fais pour gallerie mais je n'y arrive pas. 

* J'ai crée une table typicms_fileable sur base de galleryable.
* J'ai fais la relation dans mon modèle.
```
    public function files() {
        return $this->morphToMany(\TypiCMS\Modules\Files\Models\File::class, 'fileable')
                        ->withPivot('position')
                        ->orderBy('position')
                        ->withTimestamps();
    }
```
* J'ai crée un admin une vue files-fieldset.
```
{!! BootForm::hidden('files')->value('') !!}
{!! BootForm::select(
        'Fichiers',
        'files[]',
        $model->files->pluck('file', 'id')->all() + Files::getModel()->pluck('file', 'id')->all()
    )
    ->select($model->files->pluck('id')->all())
    ->multiple(true)
    ->id('galleries')
!!}
```

Mais je ne trouve pas la partie du code qui fait le lien quand tu envoi le formulaire d'ajout/edition ?

Je me suis dit alors que c’était magique, du coup, j'ai tenté d'envoyer le formulaire en sélectionnant quelques fichiers mais rien n'est ajouté dans ma table ;)

Une idée de ce que j'ai loupé ? 

Merci et bonne journée :)

**Comment by sdebacker** [comment]
Bonjour Yannick,

Tu peux utiliser la méthode syncRelation qui se trouve dans TypiCMS\Modules\Core\Repositories\RepositoriesAbstract ou bien le faire toi même dans un controller à l'aide des méthodes Laravel.

**Comment by InfinityWebMe** [comment]
Nickel, merci :D
