### ISSUE TITLE
Adding News module

### ISSUE THREAD

**Issue by aleksandar1909** [TypiCMS/Base#109]
Hi,

I have a problem with adding a News module. In a different project a half year ago I could add News with no issues. What should I do?
![news-problem](https://user-images.githubusercontent.com/8800897/33019791-24043dd2-cdfc-11e7-90a3-1b8956e76d2b.png)

Thank you in advance!

**Comment by ivarsmednis** [comment]
Hi Aleksandr. I think you are installing news module for typicms 3 for Typicms v2.9.x. 

Try installing news module v 2.9.0

**Comment by sdebacker** [comment]
Just use this command : composer require typicms/news:^2

**Comment by aleksandar1909** [comment]
Thank you, that's it! It works like it should!
