### ISSUE TITLE
2.9 - Problème de tri

### ISSUE THREAD

**Issue by InfinityWebMe** [TypiCMS/Base#111]
Bonjour,

Je rencontre un problème avec le système de tri qui est utilisé dans le cms ui-tree-node. 

Dans ListController, dans le callback dropped, j'aimerai récupérer la liste des éléments trié mais pas moyen, j'ai toujours l'ordre de l'ancienne liste quand je la parcours. 

Je rencontre un problème plutôt bizarre, dans le callback j'ai ajouté ces deux lignes.
  
```
console.log(currentList);
angular.forEach(currentList, function (model) {
      console.log(model.id);
 });
```

Le 1er console log me retourne le tableau dans le nouvel ordre :
```
[
  {
    "id": 1,
    "image": "home-bg.jpg",
    "position": 1,
    "created_at": "2017-12-28 16:01:49",
    "updated_at": "2017-12-30 10:19:33",
  },
  {
    "id": 3,
    "image": null,
    "position": 1,
    "created_at": "2017-12-29 11:33:00",
    "updated_at": "2017-12-29 11:33:00",
  },
  {
    "id": 2,
    "image": "home-bg_1.jpg",
    "position": 2,
    "created_at": "2017-12-28 16:01:59",
    "updated_at": "2017-12-30 10:19:33",
  }
]
```
Tandis que le second me retourne le tableau dans l'ordre précédent : 3, 2, 1 

Il semblerait que la liste affiché n'est pas parcourue dans l'ordre affiché dans le console.log. Du coup, pas moyen de récupérer ma liste trié. 

Auriez-vous une idée d'où pourrait provenir le soucis ? 

Merci d'avance,

Yannik

**Comment by sdebacker** [comment]
Bonjour, j'ai aussi constaté ce bug du côté d'angular-ui-tree, c'est pourquoi dans TypiCMS 3 c'est la version 2.22.5 d'angular-ui-tree qui est installée.

**Comment by InfinityWebMe** [comment]
Effectivement problème réglé, merci :)
