### ISSUE TITLE
3.0.1 - How to install it

### ISSUE THREAD

**Issue by ankha0109** [TypiCMS/Base#112]
Hello,
How to install new version with composer ? (https://github.com/TypiCMS/Base/releases/tag/3.0.1)

I'm using following command.
**composer create-project typicms/base newversion 3.0.1**

But receiving error message.

>  [InvalidArgumentException]
  Could not find package typicms/base with version 3.0.0 in a version install
  able using your PHP version 5.6.25.

**Comment by sdebacker** [comment]
Hello, TypiCMS requires PHP 7.

Samuel

**Comment by ankha0109** [comment]
@sdebacker Oh, Thank you for information.

It will support less than PHP 7 in future?

**Comment by sdebacker** [comment]
No, sorry.
