### ISSUE TITLE
Main locale in URL

### ISSUE THREAD

**Issue by aleksandar1909** [TypiCMS/Base#115]
Hi,

I have a problem with showing main locale in URL, even I set main_locale_in_url in config\typicms.php to false.

Can you tell me what could it be?

Thank you in advance

**Comment by sdebacker** [comment]
It's not in the docs, but you have to set `locale` and `fallback_locale` to the main locale you defined. Also, it must be the first locale in the array of locales set in `translatable_bootforms.php` file.

**Comment by sdebacker** [comment]
Does it solve the problem?

**Comment by aleksandar1909** [comment]
Not for now.

And I don't find that in translatable_bootforms.php because I'm using 2.9.0 version of TypiCMS.

**Comment by sdebacker** [comment]
Ok, in this case it's located in the config file `translatable.php`.

**Comment by aleksandar1909** [comment]
It's still not working although I deleted all the cache.

What else could it be?

**Comment by sdebacker** [comment]
Difficult to say…
