### ISSUE TITLE
After install 

### ISSUE THREAD

**Issue by damulhan** [TypiCMS/Base#119]
After installing at first time. I got this error message, and cannot go more:  

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>>'$.en' AS translation, `key` from `typicms_translations` where `group` = ?' at line 1 (SQL: select translation->>'$.en' AS translation, `key` from `typicms_translations` where `group` = db) (View: /var/www/temp/typicms/resources/views/errors/404.blade.php)

**Comment by sdebacker** [comment]
Duplicate of #116

**Comment by sdebacker** [comment]
Duplicate of #
