### ISSUE TITLE
How can I get Nested Menu in Admin Panel

### ISSUE THREAD

**Issue by shahkeyurc** [TypiCMS/Base#120]
Am big fan of TypiCMS, thanks for providing such a nice tool.

Can you please help me how can I add SubMenu (nested menu) for a Module which I created?

**Comment by sdebacker** [comment]
Hello, sorry for the late answer, You can check the docs of https://github.com/TypiCMS/NestableCollection and read the code of the Pages module to see how to implement such a feature.
