### ISSUE TITLE
Suggestion / request: use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [TypiCMS/Base#121]
First of all, thanks for TypiCMS!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this TypiCMS? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/Base/pulls). I'll port the `laracasts/utilities` PR over to this repo now.

I built Dependabot, but I'm honestly only suggesting it because I hope it can save you some time. I'd love any feedback, and obviously having a repo like TypiCMS using Dependabot would help boost its profile, but if it's not helpful to you then it's not really worth anything.

You can install it from [here](https://github.com/apps/dependabot) or [here](https://github.com/marketplace/dependabot) if you decide to give it a try. 🙏

**Comment by sdebacker** [comment]
Thank you but I prefer to manually manage dependencies because, you know, even minor version bump can cause breaking changes.
