### ISSUE TITLE
Db translations wrapped with doublequotes

### ISSUE THREAD

**Issue by ludmanp** [TypiCMS/Base#126]
You just made new version compatible with MariDB, it is good :) But some problees are with it.
In EloquentTranslation.php selects returnt translatiens wrapped with doulequotes both in MySQL and MariaDB.

I would added 

`            $array = array_map(function($key, $value) {
                return "{$key} => {".preg_replace('~^(\")([\s\\S]*)(\")$~', '$2', $value)."}";
            }, array_keys($array), $array);
`

before `return $array;`

**Comment by ludmanp** [comment]
I found 3 places where is conflict with MariaDB, I could fix them.

**Comment by sdebacker** [comment]
Hello, thank you for reporting, I just released version 5.0.2 of translations module, It uses JSON_UNQUOTE and JSON_EXTRACT in place of ->> operator. Does it work better ?
Can you inform me about the two other places where there are conflicts with MariaDB ?

**Comment by sdebacker** [comment]
Great. JSON queries on MariaDB will be assured by Laravel 5.8, see https://github.com/laravel/framework/pull/25517
I removed the limitation of 255 characters for translations.
Thank you for the help.

**Comment by ludmanp** [comment]
Thank you too.

**Comment by ludmanp** [comment]
Also SlugObserver::slugExists needs update for MariaDB

**Comment by sdebacker** [comment]
Hello @ludmanp, TypiCMS 6 was just released, does it work better with MariaDB?

**Comment by ludmanp** [comment]
Hello @sdebacker , looks like it is much better.
Except one thing I could not really understand. 
Overall my DB needs COLLATION utf8mb4_unicode_ci, but in Base::scopeTranslated it should be utf8_unicode_ci. So It is not working if I change database config, it needs fix exactly in this method. 
I met such situation on two different hostings with MariaDB.

Would be greate to find some solution, then it will not be necessary to publish Core module.

**Comment by sdebacker** [comment]
Hello, @ludmanp 
I'm investigating… the first to find a solution is the winner!

**Comment by sdebacker** [comment]
I win. TypiCMS/Core 6.0.3 corrects the issue.

**Comment by sdebacker** [comment]
I won nothing, it doesn't work. I reverted the commit.

**Comment by sdebacker** [comment]
I couldn't find a way to resolve this issue, maybe it's related to this MariaDB bug : https://jira.mariadb.org/browse/MDEV-14301 ?

**Comment by ludmanp** [comment]
It works well without `COLLATION` attrinute in query, it works with `COLLATION utf8_unicode_ci`.

I have changed DB collation to utf8mb4_general_ci, did not help.

Error message is `COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'utf8' `, though I can not find where character set is utf8

**Comment by sdebacker** [comment]
Here is a smaller query that cause the bug: 
```sql
SELECT JSON_UNQUOTE(JSON_EXTRACT(`translation`, '$.fr')) COLLATE utf8mb4_unicode_ci `translation_translated` FROM `typicms_translations`;
```
If you know a good way to detect the database used, we could remove the collation for MariaDB users.

**Comment by ludmanp** [comment]
The best way, I suppose, is
```
DB::select('select version()')
```
For MariaDB it looks like `10.2.17-MariaDB`

**Comment by sdebacker** [comment]
TypiCMS 6.0.4 has a 'mariadb' key in `config/typicms.php`. Set it to `true` and the collation will not be applied.

**Comment by ludmanp** [comment]
Great! It works. Thank you
