### ISSUE TITLE
Admin search/filter

### ISSUE THREAD

**Issue by ivarsmednis** [TypiCMS/Base#128]
Hi there!

I saw VUE admin search component in latest TypiCMS version but couldn't get it to work on Translations or fresh typicms:create module. Is it operational? If so - could you tell how to enable it. This is one of the things i am missing from TypiCMS v2 where i could filter/search results in admin. 

All in all - great to see fresh stuff baked in v5, thank you!

**Comment by sdebacker** [comment]
Hi @ivarsmednis,

I just make it working. Please check TypiCMS 5.0.12.
You will have to update your admin index.blade.php views and update the ItemList.vue file.

Samuel
