### ISSUE TITLE
Readme has wrong instruction for NodeJS

### ISSUE THREAD

**Issue by LaPelle** [TypiCMS/Base#129]
Hi,

I've noticed that the readme suggests to [install NodeJS](https://github.com/TypiCMS/Base/blame/master/README.md#L74) under **Installation** and then use a composer command. Under **Assets** it is suggested to install NodeJs again.

Shouldn't the first instruction to install NodeJs be a instruction to install Composer instead?

**Comment by sdebacker** [comment]
Yes, I just changed it. Thank you.
