### ISSUE TITLE
More complex image fields in Presenter

### ISSUE THREAD

**Issue by ludmanp** [TypiCMS/Base#134]
Replaceing in thimbSrc
`if (!$this->entity->$field) {`
with 
`if (!data_get($this->entity, $field)) {`

and in getPath
`if (!$model->$field) {`
with
`if (!data_get($model, $field)) {`

Allow to use these methods for images in arrays or relationships or other complex fileds.

**Comment by sdebacker** [comment]
Hello, these methods have changed in latest version of TypiCMS.

**Comment by ludmanp** [comment]
Oh... So thumbSrc do not accept image field name any more, isn't it? To use this mecanism for other images we will need to write new methods in new Presenters?

**Comment by sdebacker** [comment]
Yes it is.
