### ISSUE TITLE
Localizations files

### ISSUE THREAD

**Issue by ludmanp** [TypiCMS/Base#135]
Hi  @sdebacker , 
Is there any possibility to include other languages jsons to command `typicms:create`?
I need mostly `en.json`, `ru.json` and `lv.json`. But in some projects could be other languages.

**Comment by sdebacker** [comment]
Hello, @ludmanp,
Currently it should be done manually. The create command adds the languages found in the "objects" module. But it would be preferable to create the translations in every files found in the project. I'm open for a pull request.
