### ISSUE TITLE
Installation is not working

### ISSUE THREAD

**Issue by dslpp056193** [TypiCMS/Base#137]
When i install typicms following the guid i got some errors:
- typicms:install generate wrong .env data:
![image](https://user-images.githubusercontent.com/11080873/52663107-c64c3f00-2efd-11e9-99b0-b9cac6ea3d60.png)

And some more errors:
![image](https://user-images.githubusercontent.com/11080873/52663134-db28d280-2efd-11e9-8012-9f701bdb53bb.png)

Eventually, after "successful" installation whole website is not working. It returns 404. And i know why:
![image](https://user-images.githubusercontent.com/11080873/52663191-fb589180-2efd-11e9-94c7-9f61be62f60d.png)

Guuys, your cms looks cool in docs, but why it so hard to install it?)

**Comment by sdebacker** [comment]
TypiCMS v5.0.35 correct the first error. The second error seems to be a Windows specific issue, I replaced the command by something that should work on windows (TypiCMS 5.0.36), can you confirm it's better ? It's normal that the routes/web.php file is empty.

**Comment by dslpp056193** [comment]
All works fine, thanks!

**Comment by sdebacker** [comment]
Thanks for reporting.

**Comment by berni69** [comment]
I don't know if it's related with that but, I'm having more or less the same symptoms with the latest release.

During the installation appeared this errors (on windows)

```chmod: invalid mode: '-type'
Try 'chmod --help' for more information.
?[32mDirectory storage is now writable (755).?[39m
chmod: invalid mode: '-type'
Try 'chmod --help' for more information.
?[32mDirectory bootstrap/cache is now writable (755).?[39m
------------------
```

And then, when I try to access it, I'm getting an error 404.  There are no error log in Laravel.

**Comment by sdebacker** [comment]
Ok, so the command `chmod 755 $(find storage -type d)`doesn't work on windows. Do you have a workaround ?
