### ISSUE TITLE
Error with COLLATE utf8mb4_unicode_ci

### ISSUE THREAD

**Issue by dgtllion** [TypiCMS/Base#139]
Hi all,
Im using TypiCMS 5.0.37 with MariaDB and after installation when i click on a menu item "Pages" in the admin panel i get this error:
```
SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'utf8' (SQL: select `typicms_pages`.`id`, `typicms_pages`.`position`, `typicms_pages`.`parent_id`, `typicms_pages`.`module`, `typicms_pages`.`redirect`, `typicms_pages`.`is_home`, `typicms_pages`.`private`, 
CASE WHEN JSON_UNQUOTE( JSON_EXTRACT(`status`, '$.en') ) = 'null' THEN NULL ELSE JSON_UNQUOTE( JSON_EXTRACT(`status`, '$.en') ) END COLLATE utf8mb4_unicode_ci `status_translated` , 
CASE WHEN JSON_UNQUOTE( JSON_EXTRACT(`title`, '$.en') ) = 'null' THEN NULL ELSE JSON_UNQUOTE( JSON_EXTRACT(`title`, '$.en') ) END COLLATE utf8mb4_unicode_ci `title_translated` , 
CASE WHEN JSON_UNQUOTE( JSON_EXTRACT(`slug`, '$.en') ) = 'null' THEN NULL ELSE JSON_UNQUOTE( JSON_EXTRACT(`slug`, '$.en') ) END COLLATE utf8mb4_unicode_ci `slug_translated` , 
CASE WHEN JSON_UNQUOTE( JSON_EXTRACT(`uri`, '$.en') ) = 'null' THEN NULL ELSE JSON_UNQUOTE( JSON_EXTRACT(`uri`, '$.en') ) END 
COLLATE utf8mb4_unicode_ci `uri_translated` from `typicms_pages` order by `position` asc)
```
But when i remove `COLLATE utf8mb4_unicode_ci ` in vendor/typicms/core/src/Models/Base.php:139 the error is no longer printed.
Can someone tell me why is that collate there? and is it possible to remove it?

Regards,
Bogdan

**Comment by sdebacker** [comment]
The collation is here to sort and filter data correctly. What is you MariaDB version ? New versions of MariaDB should handle this collation correctly.

**Comment by dgtllion** [comment]
Server version: 10.3.12-MariaDB - Homebrew

**Comment by sdebacker** [comment]
Yes, the collation should be taken from the database config file. For the moment, if you change utf8 for utf8mb4 in the charset key in config.database.php, it should be ok, no?

**Comment by dgtllion** [comment]
No, i don't have `config.database.php`. Also for other projects i need utf8.

**Comment by sdebacker** [comment]
Sorry I mean config/database.php

**Comment by dgtllion** [comment]
Nah, that doesnt work too.

**Comment by sdebacker** [comment]
Does it work better with the just-released TypiCMS 6?

**Comment by trk** [comment]
I have same issue on `v6.0.1` with `10.3.14-MariaDB` (fresh installation).

For the moment i modified `Base.php` model file, working with this config (is it real solution ?)

```code
        // $collation = DB::connection()->getConfig()['collation'] ?: 'utf8mb4_unicode_ci';
        $collation = 'utf8_unicode_ci';
        foreach ($translatableColumns as $column) {
            if ($column === 'status') {
                $query
                    ->selectRaw('
                        CAST(JSON_UNQUOTE(
                            JSON_EXTRACT(`'.$column.'`, \'$.'.$locale.'\')
                        ) as UNSIGNED) as `'.$column.'_translated`
                    ');
            } else {
                $query
                    ->selectRaw('
                        CASE WHEN
                        JSON_UNQUOTE(
                            JSON_EXTRACT(`'.$column.'`, \'$.'.$locale.'\')
                        ) = \'null\' THEN NULL
                        ELSE
                        JSON_UNQUOTE(
                            JSON_EXTRACT(`'.$column.'`, \'$.'.$locale.'\')
                        )
                        END
                        COLLATE ' . $collation . ' `'.$column.'_translated`
                    ');
            }
```
**DB charset**=utf8mb4
**DB collation**=utf8mb4_unicode_ci

10.3.14-MariaDB
PHP 7.3.4
Laravel Valet 2.2.1

**Comment by sdebacker** [comment]
If your installation doesn't support utf8mb4_unicode_ci, you can change it in `config/database.php` and set `'collation' => 'utf8_unicode_ci'` for you connection. Does it work better?

**Comment by trk** [comment]
I am using `utf8mb4_unicode_ci` collation on my all projects and don't have problem with it. I want to try `TypiCMS` and installed it. Gettting this error on some admin pages not all `Pages, Translations`Menu Links`.

What you mean, `if your installation doesn't support utf8mb4_unicode_ci` ?

**Comment by sdebacker** [comment]
The new TypiCMS 6.0.4 has a 'mariadb' key in config/typicms.php. Set it to `true` and the COLLATE part of the query will not be applied.
