### ISSUE TITLE
Error install - Memcahed problem

### ISSUE THREAD

**Issue by valle6** [TypiCMS/Base#14]
I have received the error bellow during TypiCms installation:
<pre>
php composer.phar create-project typicms/base mywebsite
...
Generating autoload files
PHP Fatal error:  Class 'Memcached' not found in /var/www/projects/dev/typicms/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php on line 51

  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Memcached' not found                              

Script php artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]                                                           
  Error Output: PHP Fatal error:  Class 'Memcached' not found in /var/www/pro  
  jects/dev/typicms/vendor/laravel/framework/src/Illuminate/Cache/MemcachedCo  
  nnector.php on line 51    

php artisan typicms:install
PHP Fatal error:  Class 'Memcached' not found in /var/www/projects/dev/typicms/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php on line 51

  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Memcached' not found                              
</pre>                                    
I have tried to install Memcached. But I've recceived this message:

<pre>
aptitude install php5-memcached
The following NEW packages will be installed:
  php5-memcached{b} 
0 packages upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 39.1 kB of archives. After unpacking 151 kB will be used.
The following packages have unmet dependencies:
 php5-memcached : Depends: php5-common (= 5.5.25-1~dotdeb+7.1) but 5.6.9+dfsg-0+deb8u1 is installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     php5-memcached [Not Installed] 
</pre>

Change php5-common would produce some problems. I've tried to install only Memcached, but the error haven't changed. 

What must I do?

**Comment by sdebacker** [comment]
I don't know exactly. You can try TypiCMS without cache by set cache to false in config/typicms.php.

**Comment by valle6** [comment]
It has been impossible to install memcached in Debian 7. This is a problem with packages dependencies of my Linux (Debian 7). So, I created a new server with Debian 8.  Even installing memcached or php5-memcached, I continue receiving the quoted error, during artisan installation:

root@debian4:/var/www/projects/dev/typi# php artisan typicms:install
PHP Fatal error:  Class 'Memcached' not found in /var/www/projects/dev/typi/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php on line 51

                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Memcached' not found   

I think the installation of TypiCms Base hasn't finished. Desabling memcached only has meaning after full installation. What can I do? Don't you have this problem with a new installation?

I've received an blank page, when I access <server>/projects/dev/typi/public/index.php.

Regards

**Comment by sdebacker** [comment]
The tip is installing bower npm and gulp. I guess there is doc about that on the web.

**Comment by sdebacker** [comment]
About memcached, I'm sure you can install it with the help of docs and tuts on the web.
But I recognize I have to remove memcached dependency on TypiCMS.

**Comment by YOzaz** [comment]
@valle6 something is wrong with your PHP configuration - it's nothing to do with CMS. Memcached class is not present - which signals, that extension is not loaded. Try installing `php5-memcache` module as well, and enable it in php.ini (check if it's loaded with phpinfo() afterwards).
But in general, package should be able to detect if Memcached is not present - and shouldn't be dependent on it, as there are other caching solutions as well... Why not use Laravel Cache wrapper instead?
P.S. Don't mix PHP Memcache with Memcached - they are separate.

**Comment by sdebacker** [comment]
I use Laravel Cache wrapper, of course, but TypiCMS needs a taggable cache system like memcached or redis.
