### ISSUE TITLE
Is it possible to update laravel in the future?

### ISSUE THREAD

**Issue by Jonyorker** [TypiCMS/Base#140]
In the future, if we wish to update the underlying laravel, is it possible to do so, or do we wait till TypiCMS is updated first?

Thanks!

**Comment by sdebacker** [comment]
You can publish all module, then upgrade Laravel. I will release a new version soon.

**Comment by behnamahmadi** [comment]
any news about new version? @sdebacker

**Comment by sdebacker** [comment]
Yes, in a few days. Maybe during this week-end.

**Comment by behnamahmadi** [comment]
Good news

**Comment by sdebacker** [comment]
TypiCMS 6 is out!
