### ISSUE TITLE
Unauthenticated

### ISSUE THREAD

**Issue by mozvatic** [TypiCMS/Base#141]
If i open any link in admin, i get error: Unauthenticated, and can't list pages or open any link!

**Comment by sdebacker** [comment]
That’s really strange man. Maybe your user doesn’t have an api_token?

**Comment by mozvatic** [comment]
how i can view about that? what i can do?

**Comment by mozvatic** [comment]
i have token storen in database:  "Jj5XzPbUl7kPwLvNPPcKQ1CDwvhTV4".

success
array:4 [▼
  "ability" => "see-all-pages"
  "result" => true
  "user" => 1
  "arguments" => "[]"
]

But error is all time and loading is all time.

**Comment by sdebacker** [comment]
I don’t know what is wrong with your app, TypiCMS is a Laravel app, you should find a solution by reading some Laravel forum/docs.

**Comment by mozvatic** [comment]
Yes i search, but nowhere any solutions! i install with composer, and install other modules like sitemap,news,contacts...

**Comment by mozvatic** [comment]
[vue-i18n] Value of key 'Pages' is not a string!
[vue-i18n] Cannot translate the value of keypath 'Pages'. Use the value of keypath as default.
GET https://localhost/api/pages?fields[pages]=id,position,parent_id,module,redirect,is_home,private&locale=en&translatable_fields=status,title,slug,uri 401 (Unauthorized)

**Comment by sdebacker** [comment]
Does it work if you try to install a new TypiCMS project ?

**Comment by mozvatic** [comment]
i install new project about 3 times on 3 PC, and with all installs i get same problem. I use Laragon with PHP 7.3.1, MySQL 5.7.18. I test about 4 Laravel CMS and only Typi and i thing Asgard have problems!

**Comment by sdebacker** [comment]
I will try with Laragon and get back to you soon.

**Comment by zunky44** [comment]
>     RewriteEngine On
> RewriteCond %{HTTP:Authorization} ^(.*)
> RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

adding this code in .htaccess solved my problem.

**Comment by nicolaib** [comment]
I had this issue when running the app in a browser with dev settings (like: no cache, no cookies and more). I couldn't see any difference in what tokes were stored, but in other browser profiles without these settings, it worked fine.
