### ISSUE TITLE
Laravel Translatable

### ISSUE THREAD

**Issue by ludmanp** [TypiCMS/Base#142]
There is one problem with Spatie/laravel-translatable HasTranslations trait.
Problem:
It would be greate to show translation for fallback locale if there is no translation for current locale. But HasTranslation saves all translations, either there is null value, and detects either there is translation by existing key, but not value. So if there is null value for any translation it does not use fallback locale.

It would be greate to override HasTranslations::getTranslatedLocales method, or do not pass null translation values to model (may be using saving event).

What do you think?

**Comment by sdebacker** [comment]
Even so there is a test in Laravel/translatable : it_will_return_fallback_locale_translation_when_getting_an_empty_translation_from_the_locale() ?

**Comment by ludmanp** [comment]
Hm... It does not work for me...

**Comment by ludmanp** [comment]
I understood, sorry. It uses translatable.fallback_locale, not app.fallback_locale. There was a problem. You can close this issue

**Comment by sdebacker** [comment]
Ok. I found a bug I just corrected in core. You can composer update.

**Comment by ludmanp** [comment]
> Ok. I found a bug I just corrected in core. You can composer update.

Why you set fallback_locale to null?

**Comment by sdebacker** [comment]
If not, each null language textarea would be filled with the content of the default language.

**Comment by ludmanp** [comment]
Ok, I see
