### ISSUE TITLE
croppa image error

### ISSUE THREAD

**Issue by MauroCoder** [TypiCMS/Base#143]
Default install. Images don't show.

Croppa: Crop already exists at files/image-240x240-resize.jpg. You probably have a misconfiguration. Make sure that the URL to your crop can be transformed by the `path` config to your `crop_dir`.

**Comment by che1974** [comment]
same error
[2019-06-11 13:28:46] local.ERROR: Croppa: Crop already exists at files/firma-odp-doc-02a0ca303d24445ad4c43ba7234d1a2c-240x240-resize.jpg. You probably
                have a misconfiguration. Make sure that the URL to your crop can be
                transformed by the `path` config to your `crop_dir`. {"exception":"[object] (Bkwld\\Croppa\\Exception(code: 0): Croppa: Crop already exists at files/firma-odp-doc-02a0ca303d24445ad4c43ba7234d1a2c-240x240-resize.jpg. You probably
                have a misconfiguration. Make sure that the URL to your crop can be
                transformed by the `path` config to your `crop_dir`. at /shared/httpd/bella/vendor/bkwld/croppa/src/Bkwld/Croppa/Storage.php:184)

**Comment by che1974** [comment]
possible error in render function Croppa module.
function $this->storage->cropsAreRemote() return false, because it is a local file system and condition pass   return already cropped image.

**Comment by rafacarmona** [comment]
Same error here
I think the problem happen when you try to render a image that already exists. if u delete the 240x240 files, and refresh the page, the images should show.

@che1974, did you solve the problem?

Btw, my error here:
`Croppa: Crop already exists at files/indice-240x240-resize.png. You probably have a misconfiguration. Make sure that the URL to your crop can be transformed by the `path` config to your `crop_dir`.`

**Comment by rafacarmona** [comment]
> 
> 
> Same error here
> I think the problem happen when you try to render a image that already exists. if u delete the 240x240 files, and refresh the page, the images should show.
> 
> @che1974, did you solve the problem?
> 
> Btw, my error here:
> `Croppa: Crop already exists at files/indice-240x240-resize.png. You probably have a misconfiguration. Make sure that the URL to your crop can be transformed by the `path`config to your`crop_dir`.`

Ok, solve the error.

I deleted the "public/storage" folder and I executed the command 'php artisan storage:link'.
