### ISSUE TITLE
Extend Menu prepare

### ISSUE THREAD

**Issue by ludmanp** [TypiCMS/Base#145]
Would be greate to make 
```
$app->singleton('TypiCMS.menus', function (Application $app) {
            return $app
                ->make('Menus')
                ->published()
                ->with([
                    'menulinks' => function (HasMany $query) {
                        $query->published();
                    },
                    'menulinks.page',
                ])
                ->findAll()
                ->transform(function (Menu $menu) {
                    $menu->menulinks = app('Menus')->prepare($menu->menulinks)->nest();

                    return $menu;
                });
        });
```
as protected function to have ability extend Menus ModuleProvider to ovewriteprepare function. 
Or you can offer another way to do it?

For now I have made extensions for EloquentMenu, Menus facade and menus ModuleProvider to implement new logics, but I have to override whole register mehod to change only this place.

**Comment by sdebacker** [comment]
Hello @ludmanp,
Good idea, I'm ok for a pull request.
