### ISSUE TITLE
Section in Products

### ISSUE THREAD

**Issue by zunky44** [TypiCMS/Base#146]
Hi, Is there any way to use section in product module.

**Comment by sdebacker** [comment]
Hello, no, you have to implement this by yourself.

**Comment by zunky44** [comment]
any guidance ? i am really confused here.

**Comment by sdebacker** [comment]
Sorry, I don't provide support for TypiCMS.

**Comment by ivarsmednis** [comment]
Zunky44,  just create subpages in admin panel and loop through them like so

@foreach($page->children as $subpage)
<h3>{{ $subpage->title }}</h3>
<div>{!! $subpage->body !!}</div>
@endforeach

**Comment by ivarsmednis** [comment]
Oh sorry i misread your problem.
For products to display additional elements from db you'd have to add db fields to product table and modify _form.blade.php template.
