### ISSUE TITLE
Problem creating New Module

### ISSUE THREAD

**Issue by zunky44** [TypiCMS/Base#147]
Hi,
I created Testimonials Module using 

> php artisan typicms:create testimonials
command. and tried to link module with page but there is no testimonials module in dropdown.

**Comment by sdebacker** [comment]
Did you add the module provider in config/app.php ?

**Comment by zunky44** [comment]
> Did you add the module provider in config/app.php ?

yes, i added it to provider section above TypiCMS\Modules\Core\Providers\ModuleProvider::class.

**Comment by sdebacker** [comment]
Does the module appear in the sidebar?

**Comment by zunky44** [comment]
> Does the module appear in the sidebar?

nope. but files are generated in Module/Testimonials & View/Vendor/Testimonials folders

**Comment by sdebacker** [comment]
In this case, the module provider is not loaded. You have to find why it isn't.

**Comment by zunky44** [comment]
> php artisan config:clear
> php artisan clear-compiled

Did the trick.

**Comment by sdebacker** [comment]
Great
