### ISSUE TITLE
Issue installing typicms/categories (stable version)

### ISSUE THREAD

**Issue by zedee** [TypiCMS/Base#148]
Hi, I'm trying to install `typicms/categories` module by running `composer require typicms/categories
` but I get the following error:

```
Problem 1
    - Installation request for typicms/categories ^2.9 -> satisfiable by typicms/categories[2.9.0].
    - typicms/categories 2.9.0 requires typicms/core ~2.9.0 -> satisfiable by typicms/core[2.9.0, 2.9.1, 2.9.2, 2.9.3] but these conflict with your requirements or minimum-stability.
```

In my `composer.json` I got this require entry: `"typicms/core": "~6.0.0"`

Is there any flag or parameter for `composer` that I'm missing?

Many thanks

**Comment by sdebacker** [comment]
Hello, this module is deprecated and cannot be installed on the latest version of TypiCMS. If you want categories, please check the Projects module that have categories built-in.
