### ISSUE TITLE
File Module : folder creation fails (filesystem S3)

### ISSUE THREAD

**Issue by zedee** [TypiCMS/Base#149]
Hi, I'm trying to create a folder from the file module, but after giving writing to the _prompt_ window I'm getting this error message:

```
"message": "Found 1 error while validating the input provided for the GetObject operation:\n[Key] expected string length to be >= 1, but found string length of 0",
    "exception": "InvalidArgumentException",
    "file": "/home/projects/typi-app/vendor/aws/aws-sdk-php/src/Api/Validator.php",
    "line": 65,
```
As far as I know, I have set up correctly AWS user policies. I've been uploaded files without hassle to S3, but no luck creating folders.

I'd publish `File` module and try to investigate by myself because I suspect some missing variable being passed from the frontend prompt to backend but I'd like to confirm if there's something I'm doing wrong here.

**Comment by sdebacker** [comment]
Ok, keep me informed. FYI, folders are virtual, only stored in database, not in the real filesystem.
