### ISSUE TITLE
Online demo version

### ISSUE THREAD

**Issue by asaf050** [TypiCMS/Base#15]
Hey,
There is any online demo for this CMS?
Thanks!

**Comment by sdebacker** [comment]
You can try the 1.x version based on Laravel 4 here : http://typicms.samsfactory.com/admin (login / password: admin@example.com / admin)

**Comment by cwolfenberger** [comment]
@sdebacker http://samsfactory.com/ has phpinfo exposed.

**Comment by sdebacker** [comment]
Thank you, corrected.

**Comment by mylselgan** [comment]
> You can try the 1.x version based on Laravel 4 here : http://typicms.samsfactory.com/admin (login / password: [admin@example.com](mailto:admin@example.com) / admin)

I want to check the demo too. The above link is not working.
