### ISSUE TITLE
Adding Custom Route in Module RouteServiceProvider

### ISSUE THREAD

**Issue by zunky44** [TypiCMS/Base#150]
Hi,
I am trying to add some custom routes for Module.

>   foreach (locales() as $lang) {
>                         if ($page->translate('status', $lang) && $uri = $page->uri($lang)) {
>                             $router->get($uri, $options + ['uses' => 'PublicController@index'])->name($lang.'::index-events');
>                             $router->get($uri.'/day', $options + ['uses' => 'PublicController@day'])->name('day-event');
>                             $router->get($uri.'/night', $options + ['uses' => 'PublicController@night'])->name($lang.'::night-event');

But always getting 404 error. Any ideas to solve this problem will be highly appreciated.

**Comment by sdebacker** [comment]
Did you linked a page to this module?

**Comment by zunky44** [comment]
Yeah. Everything is working fine except custom routes which i have added. 
i.e.

> 
> $router->get($uri.'/day', $options + ['uses' => 'PublicController@day'])->name('day-event');
> $router->get($uri.'/night', $options + ['uses' => 'PublicController@night'])->name($lang.'::night-event')

**Comment by sdebacker** [comment]
Strange. I don't see what may cause this problem.
