### ISSUE TITLE
An error occurred with the data fetch 

### ISSUE THREAD

**Issue by mohdsyahid** [TypiCMS/Base#153]
I got error 

"An error occurred with the data fetch " 

when submit/save. and then css typicms not read properly.

**Comment by mohdsyahid** [comment]
Need install npm install && run dev . But still got error. And i check that error. typicms work MacOS only.

**Comment by sdebacker** [comment]
The installation process doesn't work properly on your system? What is your system?

**Comment by mohdsyahid** [comment]
> The installation process doesn't work properly on your system? What is your system?

Typicms working but got delay/icon not appear properly .

Already fix. 

(Need use macOS ) working perfect. 

I got error when use Windows
