### ISSUE TITLE
File sorting in admin

### ISSUE THREAD

**Issue by ivarsmednis** [TypiCMS/Base#157]
Hi!
Found a small issue when sorting files in admin files widget (in model edit view). The problem is that sorting doesn't take in account model_id scope and changes positions to all files with the same id, altering file order in other model files if they have same files.

I guess something like this should be added to Files -> ApiController -> sort function 
                ->where('model_id', $item['pivot']['model_id'])
                ->where('model_type', $item['pivot']['model_type'])
to change only sorting for files in particular model id

**Comment by sdebacker** [comment]
Hello Ivars, sorry for my late answer. It's fixed in typicms/files v7.0.8. Thank you.
