### ISSUE TITLE
 LogicException  : Please make sure the PHP Redis extension is installed and enabled.

### ISSUE THREAD

**Issue by mbbaraka** [TypiCMS/Base#158]
LogicException  : Please make sure the PHP Redis extension is installed and enabled.

  at C:\xampp\htdocs\cms\vendor\laravel\framework\src\Illuminate\Redis\Connectors\PhpRedisConnector.php:76
    72|     protected function createClient(array $config)
    73|     {
    74|         return tap(new Redis, function ($client) use ($config) {
    75|             if ($client instanceof RedisFacade) {
  > 76|                 throw new LogicException(
    77|                         extension_loaded('redis')
    78|                                 ? 'Please remove or rename the Redis facade alias in your "app" configuration file in order to avoid collision with the PHP Redis extension.'
    79|                                 : 'Please make sure the PHP Redis extension is installed and enabled.'
    80|                 );

  Exception trace:

**Comment by ivarsmednis** [comment]
Hello! In your .env file try changing CACHE_DRIVER to file CACHE_DRIVER=file (or some other caching types, if you have them installed)

**Comment by mbbaraka** [comment]
You are the best @ivarsmednis. It worked instantly. I battled for hours.

**Comment by skfirozz** [comment]
> You are the best @ivarsmednis. It worked instantly. I battled for hours.

can you please explain whatto change in .env file

**Comment by skfirozz** [comment]
> Hello! In your .env file try changing CACHE_DRIVER to file CACHE_DRIVER=file (or some other caching types, if you have them installed)
can you please explain what to change in .env file
this is my .env file
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:WCGqY17gPAewD/T9eGedn2PpxUzJrLRKMUmxEhq6fxM=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=fundoonotes
DB_USERNAME=root
DB_PASSWORD=Admin@12345

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

**Comment by bunday** [comment]
I ran into this, this was what worked for me:

1. Locate your `php.ini` file for your server.

2. Add `extension=redis.so` to the extension section. 

3. Save your changes. 

4. Restart the server and your application

Everything should be fine now 🎉

**Comment by skfirozz** [comment]
ok and thank you
