### ISSUE TITLE
Unable to fetch the package (laravelium/feed)

### ISSUE THREAD

**Issue by obaaa8** [TypiCMS/Base#159]
`Failed to download laravelium/feed from dist: The "https://gitlab.com/api/v4/projects/Laravelium%2FFeed/repository/archive.zip?sha=91ddec71754a60fa066d7ef0a2ea0124d7966eb0" file could not be downloaded: failed to open stream: Connection timed out`

**Comment by ivarsmednis** [comment]
Just did a fresh install and laravelium/feed installed with no issues. Maybe try installing again. Could be some network hickups.
