### ISSUE TITLE
Nginx 502 error on fresh installtion

### ISSUE THREAD

**Issue by asaf050** [TypiCMS/Base#16]
Hey,
I get 500 Error from Nginx when I install the package.
I've tried to install the original Laravel package and it works with the exact same settings.

**Comment by sdebacker** [comment]
Can you see wh

**Comment by sdebacker** [comment]
Can you see what’s the error thrown ?

**Comment by asaf050** [comment]
`2015/06/21 18:51:31 [error] 5061#0: *4 recv() failed (104: Connection reset by peer) while reading response header from$
2015/06/21 18:52:50 [crit] 5061#0: *8 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) wh$`

**Comment by asaf050** [comment]
It was server configuration error.
Set the following parameter for "try_files" fix the issues:
 try_files $uri/ $uri /index.php?$query_string;
