### ISSUE TITLE
Issue with TypiCMS::title()

### ISSUE THREAD

**Issue by runningjack** [TypiCMS/Base#160]
Return value of TypiCMS\Modules\Core\Services\TypiCMS::title() must be of the type string, null returned

I try to for the first time and i got this above what i'm i not doing right thanks

**Comment by ivarsmednis** [comment]
Hi! It must be something with database.
I guess you got a REDIS error while installing and database data did not get seeded. So maybe you can try running migrations and seeders again

**Comment by sdebacker** [comment]
It's because there are no title corresponding to the app locale present in the settings table.

**Comment by sdebacker** [comment]
I just published Core 7.0.22 that fix the problem.

**Comment by runningjack** [comment]
@ivarsmednis thank for your support issues resolved from my end and i'm good... thanks for the good job
