### ISSUE TITLE
Is Home requires slug

### ISSUE THREAD

**Issue by deveti** [TypiCMS/Base#161]
If after initial install you remove all pages and want to add new "Home" page it will require to have slug in request on save. Even with "Is Home" option set.

![image](https://user-images.githubusercontent.com/13333098/76470522-a8972500-63f0-11ea-9ed0-d44c991f6d5b.png)

Currently the only option to have Home page without slug is to manually delete it from DB.

**Comment by sdebacker** [comment]
Hello, the validation rule should be enhanced to allow empty slug when is_home is true. PR welcome.

**Comment by deveti** [comment]
@sdebacker PR prepared. Thank you.

**Comment by sdebacker** [comment]
Merged, thanks.

**Comment by deveti** [comment]
@sdebacker Thank you for this awesome project! I will try and participate as much as I can now that I am using it ;)

**Comment by sdebacker** [comment]
Nice !
