### ISSUE TITLE
php artisan view:cache exception

### ISSUE THREAD

**Issue by EdgarGrigoryan** [TypiCMS/Base#163]
When trying php artisan view:cache got an error 
 Symfony\Component\Finder\Exception\DirectoryNotFoundException  : The "/home/affiliate/affiliate/Modules/Settings/Providers/../resources/views/" directory does not exist.

**Comment by sdebacker** [comment]
Thank you for spotting. On a published package, you have to remove the line `$this->loadViewsFrom(…)` from the boot method of the ModuleProvider.

**Comment by sdebacker** [comment]
This will be fixed in next release
