### ISSUE TITLE
npm run dev : failed

### ISSUE THREAD

**Issue by punitgajjar** [TypiCMS/Base#167]
E:\xampp\htdocs\Base-master>npm run dev

> @ dev E:\xampp\htdocs\Base-master
> npm run development

> @ development E:\xampp\htdocs\Base-master
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

40% building 156/158 modules 2 active ...e-master\node_modules\sass-loader\dist\cjs.js??ref--6-4!E:\xampp\htdocs\Base-master\resources\scss\public.scss
<--- Last few GCs --->

[45800:00000299160C8200]   346603 ms: Mark-sweep 2045.8 (2053.1) -> 2043.9 (2052.8) MB, 622.3 / 0.0 ms  (average mu = 0.156, current mu = 0.016) allocat
ion failure scavenge might not succeed
[45800:00000299160C8200]   347233 ms: Mark-sweep 2045.9 (2052.8) -> 2044.0 (2052.8) MB, 625.7 / 0.0 ms  (average mu = 0.088, current mu = 0.006) allocat
ion failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF6338C4DDD]
Security context: 0x03dcb86808d1 <JSObject>
    1: List_List$from [000001A4B1511211] [E:\xampp\htdocs\Base-master\node_modules\sass\sass.dart.js:~5779] [pc=0000020AAFB63B01](this=0x039908395721 <O
bject map = 00000292ED2CF669>,0x039b46f42a69 <JSArray[1]>,0x037bdc6406e9 <false>,0x009b733ed091 <Rti map = 000000E73DB7F819>)
    2: complexIsParentSuperselector0 [000001A4B151E451] [E:\xampp\htdocs\Base-ma...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200608.165947.45800.0.001.json
Node.js report completed
 1: 00007FF632CC363F napi_wrap+128063
 2: 00007FF632C62836 public: bool _cdecl v8::base::CPU::has_sse(void)const _ptr64+35142
 3: 00007FF632C634F6 public: bool _cdecl v8::base::CPU::has_sse(void)const _ptr64+38406
 4: 00007FF633479F4E private: void _cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) _ptr64+94
 5: 00007FF633462021 public: class v8::SharedArrayBuffer::Contents _cdecl v8::SharedArrayBuffer::Externalize(void) _ptr64+833
 6: 00007FF63332E57C public: static void _cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned _int64,unsigned __int64,class v8::intern
al::Isolate * __ptr64)+1436
 7: 00007FF6333397D0 public: void _cdecl v8::internal::Heap::ProtectUnprotectedMemoryChunks(void) _ptr64+1312
 8: 00007FF6333362F4 public: static bool __cdecl v8::internal::Heap::PageFlagsAreConsistent(class v8::internal::HeapObject)+3204
 9: 00007FF63332BB13 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReas
on,enum v8::GCCallbackFlags) __ptr64+1283
10: 00007FF63332A184 public: void _cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) _ptr64+2452
11: 00007FF63334B36D public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8:
:internal::AllocationType,enum v8::internal::AllocationOrigin) __ptr64+61
12: 00007FF6330B0C51 public: class v8::internal::interpreter::JumpTableTargetOffsets::iterator & _ptr64 _cdecl v8::internal::interpreter::JumpTableTar
getOffsets::iterator::operator=(class v8::internal::interpreter::JumpTableTargetOffsets::iterator && _ptr64) _ptr64+1665
13: 00007FF6338C4DDD public: virtual bool _cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * _ptr64) __ptr64+546637
14: 0000020AAFB63B01
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/
setup/webpack.config.js`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Optimus\AppData\Roaming\npm-cache\_logs\2020-06-08T11_29_47_816Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Optimus\AppData\Roaming\npm-cache\_logs\2020-06-08T11_29_47_842Z-debug.log

If you can please let me know if any specific version of node and npm required.
Thanks

**Comment by punitgajjar** [comment]
@ivarsmednis  Thanks for your quick response.
I have checked `"@import 'public/menu-legal'"`  seems problematic. If you can please look into.

**Comment by rhughes8469** [comment]
I can confirm that on a clean install, running 'npm run dev' also fails for me with the same memory heap errors that punitgajjar is reporting. I can also confirm that removing '@import 'public/menu-legal' from public.scss does allow 'npm run dev' to complete correctly.

**Comment by sdebacker** [comment]
Dart sass is consuming a lot more memory than Node Sass. So, I switched back to Node Sass in version 7.0.39. It fixes this issue. Let me know if you find any other problems or if you have a suggestion to make it work with Dart Sass.
