### ISSUE TITLE
I have problem with route "home"

### ISSUE THREAD

**Issue by maiskiykot** [TypiCMS/Base#168]
I tried new installation TypiCms. I have errors with route "home" after installation:
Facade\Ignition\Exceptions\ViewException
Call to undefined method TypiCMS\Modules\Pages\Models\Page::isPublished() (View: /home/host1765414/ghuri.ru/htdocs/www/resources/views/vendor/core/public/_lang-switcher.blade.php) 

How fix it? Thank you!

**Comment by sdebacker** [comment]
Hello, thanks for reporting. This bug is fixed in Core v7.0.46. Just run composer update.
