### ISSUE TITLE
Admin status buttons on listings are off

### ISSUE THREAD

**Issue by deveti** [TypiCMS/Base#173]
Hi!

When I put my website live (production) I noticed that all **status** buttons were showing as off. Even though the news or a page is published, In admin it shows as a button icon off. This happens in pages, news, menu links .. everywhere.

![image](https://user-images.githubusercontent.com/13333098/96766646-af9d0180-13db-11eb-8d80-98eb49076d6c.png)
![image](https://user-images.githubusercontent.com/13333098/96766679-bd528700-13db-11eb-93ee-4a28494eb8f8.png)

This behavior also happens on the custom module I created:

![image](https://user-images.githubusercontent.com/13333098/96766744-d6f3ce80-13db-11eb-8211-aac864d19056.png)

I do not have any errors in the console nor laravel log.

The functionality of the button works. It publishes or unpublishes entity and if you do not reload the page it even shows the correct state of the button.

Can anyone help? What else can I check? I don't even have an idea how to debug it.

Thank you,
Matic

**Comment by sdebacker** [comment]
Hello, sorry for my late reply, did you manage to solve this ?

**Comment by deveti** [comment]
@sdebacker unfortunately no. Sorry for my late reply too, as I didn't have notifications on for some weird reson.

**Comment by sdebacker** [comment]
Do you have the bug with a fresh install of TypiCMS?

**Comment by deveti** [comment]
Yes.
