### ISSUE TITLE
Composer update issue

### ISSUE THREAD

**Issue by v1cc** [TypiCMS/Base#174]
I got this  Failed to execute git clone --mirror "https://***:***@github.com/Propaganistas/Laravel-Translatable-Bootforms.git.g
  it"

Any help? Thanks

![image](https://user-images.githubusercontent.com/3595636/98926207-f4ffab00-2511-11eb-9549-6c003fa519d7.png)

**Comment by sdebacker** [comment]
Yes, unfortunately the package was removed from Github. Newer versions of TypiCMS doesn't require this package anymore.

**Comment by v1cc** [comment]
Thank you for your quick response. Where can i find thr newer version of TypiCMS?

Best Regards,
Vic Chou
________________________________
