### ISSUE TITLE
  Class 'TypiCMS\Modules\Tags\Observers\TagObserver' not found

### ISSUE THREAD

**Issue by codgo** [TypiCMS/Base#181]
`nerating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error 

  Class 'TypiCMS\Modules\Tags\Observers\TagObserver' not found

  at Modules/Projects/Providers/ModuleServiceProvider.php:47
     43▕         AliasLoader::getInstance()->alias('ProjectCategories', ProjectCategories::class);
     44▕ 
     45▕         // Observers
     46▕         Project::observe(new SlugObserver());
  ➜  47▕         Project::observe(new TagObserver());
     48▕         ProjectCategory::observe(new SlugObserver());
     49▕ 
     50▕         /*
     51▕          * Sidebar view composer

      +7 vendor frames 
  8   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(TypiCMS\Modules\Projects\Providers\ModuleServiceProvider))

      +5 vendor frames 
  14  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

**Comment by sdebacker** [comment]
The TagObserver was removed from the module Project 9.0.5, just run composer update should fix it.
