### ISSUE TITLE
An error occurred with the data fetch / Content locale couldn't be set to en

### ISSUE THREAD

**Issue by CyberEkklesiaOwner** [TypiCMS/Base#182]
Hello

On back-office, I get the following errors:

- **Left Menu**: I constantly get "_An error occurred with the data fetch_" on every item click and doesn't load. The menu items are: Dashboard, Pages, Content blocks, Tags, Menu, Translations, Files, Users, Roles. None of them load. But, Add button seems to works. At least, shows some layout and saved Home Page Content. 

- **To load Home Page**, I went to 'View website' then 'back-office'. When returning to back-office also gives error "_An error occurred while loading the local pages for the editor_" with "_Content locale couldn't be set to en_". Did some changes and were saved and showed on Website Home Page. Went back to back-office, errors displayed again and Page shows with Untitled (Title) but Title(en) and Url (en) are fine. 

- **Top Menu**: On profile link I get: "_Content locale couldn't be set to en_" when loading. The user role is Superuser and saves profile data changes.

**Comment by sdebacker** [comment]
Hello, sorry for my late reply, did you manage to solve this?
