### ISSUE TITLE
blade templates are not parsed

### ISSUE THREAD

**Issue by sohaibafifi** [TypiCMS/Base#19]
After a clean installation. My admin dashboard shows variables from the template without parsing them. Something like : 
{{ model.created_at | dateFromMySQL:'short' }}	{{ model.title }} {{ model.title }} ({{ model.locale }})	{{ model.historable_table }}	 {{ model.action }}	{{ model.user_name }}

Any solutions ?
Thank you

**Comment by sdebacker** [comment]
This is a javascript problem, this is not blade but angular vars. If the components.min.js was regenerated by Gulp, try to put the original file back and see if it works.

**Comment by sohaibafifi** [comment]
running again bower than gulp solved the problem.
Thank you
