### ISSUE TITLE
Home Page Setup

### ISSUE THREAD

**Issue by virgiltu** [TypiCMS/Base#197]
I dont know how to do this but settings should have a drop down asking what the language home page of the website is. Than if you go to domain.com it will take you to domin.com/en or /fr. there is really no reason to select a language if you already know the main language.

**Comment by sdebacker** [comment]
Hello, TypiCMS should redirect to the browser language, so domain.com should redirect to domain.com/fr if the browser is in french. If the browser’s language is not managed by you TypiCMS’s website domain.com should redirect to the first language of `config('typicms.locales')` that should be the same as `config('app.locale')`.

You can also disable the automatic redirect and choose to have domain.com = the page in the main locale, and domain.com/fr for the homepage in french. To do so, you have to set `config('typicms.main_locale_in_url')` to `false`.

I hope this gives you an answer to your questions?

**Comment by virgiltu** [comment]
Thank you so much. My config is set to true "'main_locale_in_url' => true," however the first page seems to always be the page where you have to select a language. This is why i was asking. I have not been able to get it to recognize the language automatically.

**Comment by sdebacker** [comment]
Juste uncheck "Lang Chooser" in `/admin/settings`

**Comment by virgiltu** [comment]
> Just uncheck "Lang Chooser" in /admin/settings

where is this file locate? I looked at every folder in the project.

**Comment by sdebacker** [comment]
It’s not a file, but a URL.
