### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by londoh** [TypiCMS/Base#2]
thanks very much for this, been looking forward to it.

But it doesnt install. I downloaded zip, unzip and...
```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - typicms/base v2.0.0 requires typicms/core ~1.8 -> no matching package found.
    - Installation request for typicms/base 1.0.0 -> satisfiable by typicms/base[1.0.0].
    - typicms/files v2.0.0 requires typicms/core ~2.0.0 -> satisfiable by typicms/core[v2.0.0, v2.0.1, v2.0.2].
    - typicms/core v2.0.0 requires typicms/base ~2.0.0 -> satisfiable by typicms/base[v2.0.0, v2.0.1, v2.0.2, v2.0.3].
    - typicms/core v2.0.1 requires typicms/base ~2.0.0 -> satisfiable by typicms/base[v2.0.0, v2.0.1, v2.0.2, v2.0.3].
    - typicms/core v2.0.2 requires typicms/base ~2.0.0 -> satisfiable by typicms/base[v2.0.0, v2.0.1, v2.0.2, v2.0.3].
    - Can only install one of: typicms/base[v2.0.1, 1.0.0].
    - Can only install one of: typicms/base[v2.0.2, 1.0.0].
    - Can only install one of: typicms/base[v2.0.3, 1.0.0].
    - Installation request for typicms/files ~2.0.0 -> satisfiable by typicms/files[v2.0.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by londoh** [comment]
sorry maybe my bad. Because if I follow docs and do
>composer create-project typicms/base mywebsite

then it does progress.
altho running composer update afterwards will hit same wall.

so using create-project the packages are pulled in
but then app (eg: php artisan) hits this for some reason:
>PHP Fatal error:  Class 'Laracasts\Utilities\JavaScript\JavaScriptServiceProvider' not found in /home/londoh/Development/www/l5typi/laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 150

I dont see why - laracasts/utilities has been pulled in and namespaces look correct

and another small prob: the .env file doesnt get created

**Comment by londoh** [comment]
and it looks like short of News
>FatalErrorException in 7ec587fba62e588b09b63c915e6c4d8d line 7: Class 'News' not found

**Comment by sdebacker** [comment]
Thanks for your feedback, I will check that asap.

**Comment by londoh** [comment]
and a typo in 
Providers/CoreServiceProvider.php

```php
$app->view->creator('core::admin._sidebar', 'TypiCMS\Composers\SideBarViewCreator');
```

...SidebarView...

**Comment by sdebacker** [comment]
JavascriptServiceProvider and Sidebar typos are corrected.

**Comment by sdebacker** [comment]
Does it work better via composer create-project ?

**Comment by londoh** [comment]
create-project? ... yes it does. as per my 2nd post it does progress further but still hits the wall

**Comment by sdebacker** [comment]
you can try with: 
composer create-project typicms/base:2.0.4 mywebsite

**Comment by sdebacker** [comment]
Just pushed typicms/core 2.0.5 that fixes the issue.

**Comment by londoh** [comment]
ok thanks.
that seems to fix most issues.
just on the frontend
>FatalErrorException in 7ec587fba62e588b09b63c915e6c4d8d line 7: Class 'News' not found

7ec587... = 
resources/views/vendor/pages/public/home.blade.php

News isnt being pulled in (its not required anywhere I can find)
so if I remove the calls to 'News' it seems Events also isnt available

thanks for your efforts

regards

l.

**Comment by londoh** [comment]
so if I do a manual require for news and events, and add the module providers, then after that:

I can create page, news, event. File upload, image insert etc all work, 
no log or console errors as far as I saw, 
all looks good

in fact it looks great! - thank you again for your work on this

I give it another go tomorrow
(I guess you dont need a pr for those bits)

**Comment by sdebacker** [comment]
That's now corrected.
