### ISSUE TITLE
Installation of Categories module failed because of conflicts

### ISSUE THREAD

**Issue by parsester** [TypiCMS/Base#200]
I try to install Categories but get this errors:
`typicms/categories 2.9.0 requires typicms/core ~2.9.0 -> found typicms/core[2.9.0, 2.9.1, 2.9.2, 2.9.3] but it conflicts with your root composer.json require (~9.0.0).`

how can I fix it?

**Comment by sdebacker** [comment]
Hello the module typicms/categories is deprecated. Please see typicms/projects to see how to develop categories system with Laravel/TypiCMS.

**Comment by parsester** [comment]
I see that link, there is not any docs about how to develop a categories system, what's your mean?

**Comment by sdebacker** [comment]
TypiCMS has no documentation. So you must have a good knowledge of Laravel to be able to extend it.
