### ISSUE TITLE
How can add Attributes for Projects?

### ISSUE THREAD

**Issue by parsester** [TypiCMS/Base#201]
I want to can add Multi Attributes for a Project in Projects add like as tags but with a difference, attributes should be define as a key and for each project get value like as product attributes in shops, an attribute can add for product A but don't add for product B or add to both, for example I want to add Project A, and add attribute City and type New York for it,  and add Project B and type Seattle, and as example add more attributes for a project and show all as a table in front end.

how can I do this with TypicCMS?

**Comment by sdebacker** [comment]
This is not managed by TypiCMS out of the box. You have to implement it by yourself.
