### ISSUE TITLE
TypiCMS 9.0.28 - Stored XSS at FristName parameter 

### ISSUE THREAD

**Issue by noobpk** [TypiCMS/Base#202]
Description: The user's first_name parameter can insert malicious scripts and store them on the server that are triggered when the user visits the dashboard page.

Image Request /Response
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/31820707/130639828-6c8a7665-5015-46c7-97eb-6cb0ea93e816.png">

Image Trigger XSS: 
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/31820707/130639395-66a7f17e-1c42-4a0b-a093-87f2aa011ce7.png">

**Comment by sdebacker** [comment]
Thank you for spotting, it's fixed in 9.0.30.
