### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by yeremiapinggi** [TypiCMS/Base#206]
Do you have a documentation about publi structure site and how to customize the public site 🙏🏾

**Comment by sdebacker** [comment]
Unfortunately there is no documentation for that. But if you know Laravel, you should be ok.

**Comment by yeremiapinggi** [comment]
is this template layout of page?

![Screen Shot 2021-09-13 at 14 02 27](https://user-images.githubusercontent.com/5475769/133042540-555fa8f7-eecc-4282-8556-5d8ea8374685.png)

i want to add my custom template, where can i add more template list?

**Comment by sdebacker** [comment]
/resources/views/vendor/pages/public/

**Comment by yeremiapinggi** [comment]
ok got it, so the template data load from blade file

thnks bro
