### ISSUE TITLE
Module routes are not considered

### ISSUE THREAD

**Issue by sohaibafifi** [TypiCMS/Base#21]
Except the admin url, all the module routes are ignored and not even shown using 'php artisan route:list' 
Only the pages route is considered and it looks like it is overriding the others. Trying events/{slug} for example throw a 404 error. 

... 

GET|HEAD | {uri}||TypiCMS\Modules\Pages\Http\Controllers\PublicController@uri|publicAccess,publicLocale |

**Comment by sohaibafifi** [comment]
Adding a page then using the module solved the problem.

**Comment by Lucas1314FN** [comment]
Can you explain the solution please? Thanks
