### ISSUE TITLE
why tags module (model) has not translations?

### ISSUE THREAD

**Issue by parsester** [TypiCMS/Base#215]
hello, I want to know why you don't make tags model transable? for example I want to publish a news in 2 language Persian and English and use same tag in both languages and in another hand when I load admin in Persian, titles of tags in Persian load in select input and when I load admin in English, the same tags load but in English.

Can I customize Tags module to support tranlation? I mean is it logically correct?

**Comment by sdebacker** [comment]
The tags module is currently not translatable so that it's easier to create tags on the fly.
