### ISSUE TITLE
Error after fresh installation 

### ISSUE THREAD

**Issue by dev3k** [TypiCMS/Base#216]
after 
`composer create-project typicms/base newproject`

the following error appears and the end
` SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) (SQL: select * from typicms_pages where module is not null)`

i changed the password in .env, then i got the following error
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'typicms.typicms_pages' doesn't exist (SQL: select * from typicms_pages where 'module' is not null)`

the error happens in 
/vendor/typicms/core/src/Providers/ModuleServiceProvider.php line 133

> $this->app->singleton('typicms.routes', function () {
>             return Page::with('images', 'documents')
>                 ->where('module', '!=', null)
>                 ->get();
>         });
> 

not sure why its there and runs in every console commands like `php artisan migrate`

Laravel: 8.70.1
PHP: 8.0.10

**Comment by sdebacker** [comment]
Thanks for reporting, it should be fixed now.
