### ISSUE TITLE
How to use module news to create category and page?

### ISSUE THREAD

**Issue by mauphung** [TypiCMS/Base#219]
Hi,
I already installed TinyCMS core release 9.0.44, module news and module cats as per the installation guide. It look OK.
I tried to access url htpp://localhost/tinycms/public, it display the Home page without css
I want to use news to create some categories and the pages of each category, please tell me how to do it?

**Comment by mauphung** [comment]
Any user document guide or book How to use tinyCMS available?

**Comment by sdebacker** [comment]
TypiCMS doesn't work in a subfolder. Unfortunately there is currently no complete documentation.
