### ISSUE TITLE
News Module throwing a 404 error

### ISSUE THREAD

**Issue by Lucas1314FN** [TypiCMS/Base#220]
Hi! I'm trying to use this cms. I have installed the News module, published and those stuff written in documentation. If i create a new entrance in Admin/News and try to keep the convention localhost/en/news/new-slug it does not works, throws a 404 error. I've tryed everything, re-installed like 10 times and never worked.
I'm a little obfuscated 'cause i've been hours trying to make this work.
If anybody can help me, i'll appreciate so much, really. Thanks.

**Comment by Lucas1314FN** [comment]
Hi! I've found an error (i guess). On the News module provider there's an if($page = TypiCMS::getPageLinkedToModule('news')) {
} i added an else an writted a dd($page). This dd() is returning null. I mean, the getPageLinkedToModule('news') is not getting anything from News.

**Comment by sdebacker** [comment]
Yes, you have to create a page and choose "News" as module for this page.

**Comment by Lucas1314FN** [comment]
Thanks for answer! Can you tell me how please?

**Comment by Lucas1314FN** [comment]
I'm an idiot, thank you so much man!
