### ISSUE TITLE
View [public._social-links] not found.

### ISSUE THREAD

**Issue by Lucas1314FN** [TypiCMS/Base#223]
Hey, it's me again with other problem that i can't resolve. I linked a page to the news module and well, i can now see the news list on that page but when i click they it throws an exception of this type <<InvalidArgumentException
View [public._social-links] not found. (View: D:\Trememote\NLV2\resources\views\vendor\news\public\show.blade.php)>>

![1](https://user-images.githubusercontent.com/96259152/146938328-54ff9f3b-4ad8-47f1-9b3a-344d816c9375.png)
![2](https://user-images.githubusercontent.com/96259152/146938335-58f32c18-38ac-4628-9600-0e23bb42346b.png)

I don't know what's happening, i have published the news and that show.blade.php it's on the folder.

If i can get this to work i'm sure i will never leave this cms hahaha
Thanks!

**Comment by sdebacker** [comment]
Thanks for reporting, it's now corrected in the latest version of News and Events modules. You have to replace ```@include('core::public._social-links')``` by ```@include('core::public._share-links')``` in ```show.blade.php```

**Comment by Lucas1314FN** [comment]
Wohoo you're the best man, i love you. I will support you at anytime

**Comment by sdebacker** [comment]
Thanks, the Sponsor button is just at the top of this screen ! 😘
