### ISSUE TITLE
Admin routes issue

### ISSUE THREAD

**Issue by EdgarGrigoryan** [TypiCMS/Base#232]
Hi.
We have an issue in php artisan rout:cache 
Exception  Bellow 

 LogicException 

  Unable to prepare route [admin/{uri}] for serialization. Another route has already been assigned name [admin::].

  at vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:219
    215▕             $route->name($this->generateRouteName());
    216▕ 
    217▕             $this->add($route);
    218▕         } elseif (! is_null($symfonyRoutes->get($name))) {
  ➜ 219▕             throw new LogicException("Unable to prepare route [{$route->uri}] for serialization. Another route has already been assigned name [{$name}].");
    220▕         }
    221▕ 
    222▕         $symfonyRoutes->add($route->getName(), $route->toSymfonyRoute());
    223▕

      +19 vendor frames 
  20  artisan:37
There is 2 routes by name admin::

![image](https://user-images.githubusercontent.com/4749161/168987872-de0bb1a2-57de-41f8-b436-f8aa7e8e31a4.png)

Thank you

**Comment by sdebacker** [comment]
Thanks for reporting, it's fixed by Core version 10.0.7.
