### ISSUE TITLE
An error occurred with the data fetch.

### ISSUE THREAD

**Issue by nedarta** [TypiCMS/Base#237]
Hi! 

This is related to #182 . I have the same issue.
I have a fresh installation (version from July 14th, '22), followed the installation guide, but content isn't loading:

- PHP 7.4 (started with PHP 8.1, PHP 8.0 but without luck) with all required extensions installed;
- Apache/2.4.38 (Debian)
- MariaDB 10.3.34

This is what I see on each section, except Settings
![image](https://user-images.githubusercontent.com/16962105/179168540-4eca51aa-bc77-497e-9d11-81501364c6c7.png)

Thank you in advance.

**Comment by sdebacker** [comment]
What do you see in the browser console ?

**Comment by hrmiraj** [comment]
GET http://localhost/api/history?sort=-created_at&fields[history]=history.id,history.created_at,history.title,history.locale,history.historable_id,history.historable_type,history.action,history.user_id&include=historable&page=1&per_page=100& 404 (Not Found)


My project path http://localhost/alhashmani/public/admin/dashboard

APP_URL  http://localhost/alhashmani

**Comment by hrmiraj** [comment]
Resolved, Use root domain or use virtual host on local server to resolve this issue.
