### ISSUE TITLE
Issue getting public custom module page 404

### ISSUE THREAD

**Issue by hrmiraj** [TypiCMS/Base#239]
Hi,
I have created a custom module "Products" and added some products. Now I'm trying to view the product page but get a 404
I tried the following URLs:
/en/products/slug
/product/slug
/en/product/slug

Thanks in advance

**Comment by sdebacker** [comment]
Hello, you have to create a page linked to the projects module.

**Comment by hrmiraj** [comment]
@sdebacker Thanks, I have created a page and selected a module. It's getting all the products on this URL /products. How to get a single product?
