### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by YounessTayer** [TypiCMS/Base#250]
Hi;

Process installation fail, because in step 5, when I try to enter a password and hit Enter it didn't validate it.
Thank you for your support.

Setting up database...

 Enter a database name [cms]:
 > news

 What is your MySQL address? [127.0.0.1]:
 > 127.0.0.1

 What is your MySQL port? [3306]:
 > 

 What is your MySQL username? [root]:
 > 

 What is your MySQL password? [<none>]:
 > /

**Comment by dassudip2001** [comment]
what type of error
