### ISSUE TITLE
How to create a custom module with multiple word name like `NewsletterSubscribes`?

### ISSUE THREAD

**Issue by bibekstan** [TypiCMS/Base#252]
I wanted to create a custom module with multiple word name like `NewsletterSubscribes` that can create a model NewsletterSubscribe with database table as `newsletter_subscribes`. Along with this, sidebar and its respective translation should follow a convention like `Newsletter Subscribes`.

**Comment by sdebacker** [comment]
That is currently not managed by the command `php artisan typicms:create NewsletterSubscribes`, but it's a great idea. I'm open for a pull request.
