### ISSUE TITLE
problem when compile scss

### ISSUE THREAD

**Issue by mohjam2005** [TypiCMS/Base#257]
settings:14     GET http://127.0.0.1:8000/css/admin.css net::ERR_ABORTED 404 (Not Found)
settings:398     GET http://127.0.0.1:8000/js/admin.js net::ERR_ABORTED 404 (Not Found)
settings:402 Uncaught ReferenceError: alertify is not defined
    at settings:402:13
(

**Comment by sdebacker** [comment]
We need more info.

**Comment by mohjam2005** [comment]
![لقطة الشاشة 2023-05-05 225654](https://user-images.githubusercontent.com/65953539/236557286-f6889aae-5c93-4517-a925-03f9a5ebc9dc.png)

**Comment by sdebacker** [comment]
Yarn install or npm install ?
