### ISSUE TITLE
Installation Failed Class 'Memcached' not found

### ISSUE THREAD

**Issue by matrixbegins** [TypiCMS/Base#26]
I tried `composer create-project typicms/base`. I am getting an error 
`PHP Fatal error:  Class 'Memcached' not found in /var/www/typicms/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php on line 51`

I don't have php5-memcached extension installed. However My point is I don't want to use Memcache What If I want to use redis. Can you please suggest what else should I do to make it work

**Comment by sdebacker** [comment]
What you need for redis is explained here: http://laravel.com/docs/5.1/redis
Then you will have to change CACHE_DRIVER to redis in your .env file.

**Comment by matrixbegins** [comment]
@Samuel its installation error. .evn file I'd configure after installation.
(in general, it can be done before also.) The idea is installation
shouldn't fail because one driver is not installed. Or we can have a
dependency check pre-install

Thanks & Regards,

Ankur Pandey

**Comment by sdebacker** [comment]
Yes it should be corrected.

**Comment by c1t1zen** [comment]
it's not worked out
this class not loaded in latest xampp version

**Comment by coldmake** [comment]
@c1t1zen The document states: 
Requirements: Memcached, Redis or APC
So please make sure any of those, and corresponding composer package is installed, which are outside of xampp

**Comment by c1t1zen** [comment]
but how can i do that on windows 7 i tryed many times but with no luck

thank you in advance

**Comment by sdebacker** [comment]
As of TypiCMS 2.5, It’s fixed, default cache driver is set to array. https://github.com/TypiCMS/Base/commit/bbbd0451cef8771e6395d18f1fcc12f239008405

**Comment by c1t1zen** [comment]
it means i can use it without Memcached or Redis?
coz i need to use it in shared hosting and all sheared hosting not wiht Memcached or Redis?

**Comment by sdebacker** [comment]
Yes you can use it without Memcached or Redis.

**Comment by c1t1zen** [comment]
it wokrs out, thank you

another issue i tried to install news module but database table cannot  to migratate
and if i install any module, Should  all modules located in typicms/modules/module-name ?

for ex : id i installed news module it should be in typicms/modules/news ?

typicms is project name / project folder

Thank you in advance

**Comment by sdebacker** [comment]
No, it should not necessarily be in Modules dir. Only customs module you create can be there.

**Comment by c1t1zen** [comment]
it seems all modules under vendor/typicms
so what if i need to modify or make new relationship between typiCMS where i do that?

**Comment by sdebacker** [comment]
You should copy the src dir to the Modules directory and rename it to your module name, then remove the module from composer.

**Comment by c1t1zen** [comment]
:+1: Thank you ,
so why the modules folder is empty?
some applications make packages or modules as  a part of project.
this is an example : http://sky.pingpong-labs.com/docs/2.0/modules

**Comment by sdebacker** [comment]
Perhaps for the next version I will use pingpong-labs/modules package.
