### ISSUE TITLE
Modules working with Laravel 10 ?

### ISSUE THREAD

**Issue by mobunti** [TypiCMS/Base#265]
Hi

Ive just installed TypiCMS today and went to add in a few of the optional modules and when I tried to add the sitemap I got these last 2 lines

```
    - typicms/sitemap[8.0.0, 9.0.0, ..., 9.0.4] require laravel/framework ~8.0 -> found laravel/framework[v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.7.1).
    - Root composer.json requires typicms/sitemap * -> satisfiable by typicms/sitemap[1.8.0, v1.8.5, v1.8.6, v2.0.0, ..., 2.9.0, 3.0.0, 3.0.1, 3.0.2, 4.0.0, 5.0.0, 5.0.1, 6.0.0, 7.0.0, 7.0.1, 8.0.0, 9.0.0, ..., 9.0.4].

```

Is there any way I can install the modules without breaking things ? News looks like it worked I think

**Comment by zaidhaziq** [comment]
Laravel 7 is compatible with PHP versions 7.2.5 and higher. If you want to use PHP 8.0, it's recommended to upgrade to Laravel 8.

**Comment by sdebacker** [comment]
The Blocks module is part of Core, no need to install it.

**Comment by mobunti** [comment]
> Laravel 7 is compatible with PHP versions 7.2.5 and higher. If you want to use PHP 8.0, it's recommended to upgrade to Laravel 8.

Its on laravel 10 and php 8.2 - it seemed to be complaining that sitemap required laravel 9 not laravel 10 - however @sdebacker's reply answered the question that its included in the core so all good thanks.
