### ISSUE TITLE
database COLLATION error

### ISSUE THREAD

**Issue by alagoroChapela** [TypiCMS/Base#268]
` SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'utf8' (Connection: mysql, SQL: select `id`, `key`, 
                                CASE WHEN
                                JSON_UNQUOTE(
                                    JSON_EXTRACT(`translation`, '$.en')
                                ) = 'null' THEN NULL
                                ELSE
                                JSON_UNQUOTE(
                                    JSON_EXTRACT(`translation`, '$.en')
                                )
                                END COLLATE utf8mb4_unicode_ci
                                AS `translation_translated`
                             from `typicms_translations` order by `key` asc limit 100 offset 0) {
    "userId": 1,
    "exception": {
        "errorInfo": [
            "42000",
            1253,
            "COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'utf8'"
        ],
        "connectionName": "mysql"
    }
}`
just installed. accesed to /admin. Tried to add Page

**Comment by sdebacker** [comment]
Your database should use utf8mb4.
