### ISSUE TITLE
Update readme file about Galleries.

### ISSUE THREAD

**Issue by mylselgan** [TypiCMS/Base#269]
Detail about Galleries was removed in readme file with the following commit. 

I don't know whether Galleries option still available or not.

https://github.com/TypiCMS/Base/commit/3b4408ae9f2d1debc4b86d66a9edfdda71091f64

Please update the readme file about Galleries accordingly.

**Comment by sdebacker** [comment]
Done.

**Comment by mylselgan** [comment]
Galleries is removed? but why? it will be very useful if you make plugin just to add only image formats with alt tags. We can pull those images and alt tags from database and build a gallery ourself.
