### ISSUE TITLE
list view of page and translation not showing 

### ISSUE THREAD

**Issue by cruxster** [TypiCMS/Base#276]
when i click on page and translation  link its not showing list view 

showing this error:

[12:14:41] LOG.error: SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'utf8' (Connection: mysql, SQL: select `id`, `position`, `parent_id`, `module`, `redirect`, `is_home`, `private`, 
                                CAST(JSON_UNQUOTE(
                                    JSON_EXTRACT(`status`, '$.en')
                                ) AS UNSIGNED) AS `status_translated`
                            , 
                                CASE WHEN
                                JSON_UNQUOTE(
                                    JSON_EXTRACT(`title`, '$.en')
                                ) = 'null' THEN NULL
                                ELSE
                                JSON_UNQUOTE(
                                    JSON_EXTRACT(`title`, '$.en')
                                )
                                END COLLATE utf8mb4_unicode_ci
                                AS `title_translated`
                            , 
                                CASE WHEN
                                JSON_UNQUOTE(
                                    JSON_EXTRACT(`slug`, '$.en')
                                ) = 'null' THEN NULL
                                ELSE
                                JSON_UNQUOTE(
                                    JSON_EXTRACT(`slug`, '$.en')
                                )
                                END COLLATE utf8mb4_unicode_ci
                                AS `slug_translated`
                            , 
                                CASE WHEN
                                JSON_UNQUOTE(
                                    JSON_EXTRACT(`uri`, '$.en')
                                ) = 'null' THEN NULL
                                ELSE
                                JSON_UNQUOTE(
                                    JSON_EXTRACT(`uri`, '$.en')
                                )
                                END COLLATE utf8mb4_unicode_ci
                                AS `uri_translated`
                             from `typicms_pages` order by `position` asc) {
    "userId": 1,
    "exception": {
        "errorInfo": [
            "42000",
            1253,
            "COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'utf8'"
        ],
        "connectionName": "mysql"
    }
}
![Untitled](https://github.com/TypiCMS/Base/assets/16409442/77397a29-aef4-49f0-b930-39347ae737a8)

**Comment by sdebacker** [comment]
If you are using MariaDB you can try to enable MariaDB mode in config/typicms.php.
