### ISSUE TITLE
Method Illuminate\Database\Schema\MySqlBuilder::getAllTables does not exist.

### ISSUE THREAD

**Issue by silicahd** [TypiCMS/Base#279]
When trying to install i keep getting this, Any ideas what is causing this. 

I am trying to install it using mysql. 

getalltables is not a laravel 11 function

https://laravel.com/api/10.x/Illuminate/Database/Schema/Builder.html#method_getAllTables

![image](https://github.com/TypiCMS/Base/assets/7761519/208ec287-e20f-4c83-a0c0-c820bf46e346)

**Comment by sdebacker** [comment]
No idea, I never saw this error.

**Comment by silicahd** [comment]
i found the issue. Laravel 11 no longer has this function. 

The issue is Line 113 
https://github.com/TypiCMS/Core/blob/master/src/Commands/Database.php

`  // Migrate DB
        if (count(Schema::getAllTables()) !== 0) {
            error('The database ' . $dbName . ' is not empty, no migration and seed were done.');
        } else {
            $this->callSilently('migrate');
            $this->callSilently('db:seed');
            info('The database ' . $dbName . ' was migrated and seeded.');
        }`

The getAllTables has to be changed since laravel 11 no longer supports this function. In my case I just removed it but should be fixed.

**Comment by silicahd** [comment]
Not something major but I also realized that in the database>migrations files the ->default(new Expression('(JSON_OBJECT())')) is called. This causes most MySQL database to not work. But Json was introduced in MYSQL5.7. Replacing that with ->nullable(); allows the cms to also work on MySQL 6 and lower. This idea here is that most VPS systems that are smaller usually have 2gb ram and MySQL 5.7 works with less than 1gb. Going to MySQL 6 and up requires more ram. 

` public function up(): void
    {
        Schema::create('blocks', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->json('status')->default(new Expression('(JSON_OBJECT())'));
            $table->json('body')->default(new Expression('(JSON_OBJECT())'));
            $table->timestamps();
        });
    }`

**Comment by silicahd** [comment]
Not sure why but if you clone the repo it will do this however if you use the instructions to create a new application this is not an issue. So make sure not to just clone the repo.
