### ISSUE TITLE
could i install Typicms on shared hosting?

### ISSUE THREAD

**Issue by c1t1zen** [TypiCMS/Base#29]
i have install other projects like yours and it was laravel 5 and it works but this one i can not becauase i have to install Node and Bower think it wont work out 

i hope any suggestion for that

Thank you in advance

**Comment by sdebacker** [comment]
You don't need Node and Bower on your production server.

**Comment by c1t1zen** [comment]
so when i install TypcCMS they on cmd or putty ssh it failed to config and complete the installaion
any another way to insall without "php artisan typicms:install" ???

**Comment by sdebacker** [comment]
You can install everything on your local environment then copy the files on the production server, or install TypiCMS manually like any other Laravel app.
