### ISSUE TITLE
Problems with php artisan typicms:install

### ISSUE THREAD

**Issue by LarryTX** [TypiCMS/Base#3]
I'm having problems with your artisan typicms:install command. Specifically, when I respond to the prompts for Database Name, Username, and Password, it fails with the message:
```
 [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for u
  ser ''@'localhost' to database 'assist' (SQL: CREATE DATABASE IF NOT EXISTS
   `assist`)
```
Please note that I get this message ***despite the fact that I typed in a username and password***. Am I doing something wrong or is there something else that I should be doing?

**Comment by sdebacker** [comment]
Can you give me more info about your config ? Did you manually fill .env file before install script ?

**Comment by fligen** [comment]
Im getting the same issue, following the directions to a T. 
                                                                                                                                         
  [Illuminate\Database\QueryException]                                                                                                     
  SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user ''@'localhost' to database 'laravelcms' (SQL: CREATE DAT  
  ABASE IF NOT EXISTS `laravelcms`)                                                                                                        
                                                                                                                                                                                                                                                     
  [PDOException]                                                                                                          
  SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user ''@'localhost' to database 'laravelcms' 


also the username i type in is not the one that shows up in the error.

**Comment by sdebacker** [comment]
For now you can manually fill .env fill and rerun the installation command.

**Comment by sdebacker** [comment]
Should be fixed
