### ISSUE TITLE
Installation: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

### ISSUE THREAD

**Issue by mbaxter91288** [TypiCMS/Base#32]
Hi,

I am trying to install the CMS on local machine, using MAMP and get the following error after being asked for my database password:

```
SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected
```

I've tried including the below snippet within the config/database.php file, which helps (as without it I get a different error), but doesn't resolve this issue.

```
'unix_socket'   => '/Applications/MAMP/tmp/mysql/mysql.sock',
```

Any help would be greatly appreciated.

Regards,
Mat

**Comment by sdebacker** [comment]
Did you create the database before installing TypiCMS? If yes, can you try without creating the database and let the installer create it?
I will install MAMP and see what's wrong. Keep me informed.

**Comment by freel132** [comment]
well i have same issue. trying to add everything manually. I will keep update.
