### ISSUE TITLE
[PDOException] SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

### ISSUE THREAD

**Issue by ayimdomnic** [TypiCMS/Base#34]
hello,
Good Job with the CMS. However, I keep getting the above error when installing the db. what could be the issue.. or is it a problem with Mamp?

Thanks

**Comment by sdebacker** [comment]
You are not the first to encounter an error of this kind with mamp: https://github.com/TypiCMS/Base/issues/32

**Comment by ayimdomnic** [comment]
any other way to go about it?

**Comment by sdebacker** [comment]
Yes you can install TypiCMS manually like any other Laravel app.

**Comment by ayimdomnic** [comment]
yup, works perfectly... thanks

**Comment by sdebacker** [comment]
You’re welcome
