### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found:

### ISSUE THREAD

**Issue by chrismedina** [TypiCMS/Base#36]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hrv_social.typicms_pages' doesn't exist (SQL: select * from `typicms_pages` where (select count(*) from `typicms_page_translations` where `typicms_page_translations`.`page_id` = `typicms_pages`.`id` and `status` = 1 and `locale` = en) >= 1 and `module` != )

This occurs on either manual installation or attempt @ auto installation on Laravel Framework version 5.1.26 (LTS).  Any direction would be helpful.

**Comment by sdebacker** [comment]
It's a bug I plan to correct today.

**Comment by sdebacker** [comment]
Should be fixed.

**Comment by sdebacker** [comment]
Now It should work with Core 2.5.11. Just run composer update. Is it ok ?

**Comment by chrismedina** [comment]
Yep it's running like a champ now, thanks.
