### ISSUE TITLE
Script php artisan clear-html handling the post-install-cmd event returned with an error

### ISSUE THREAD

**Issue by webfactorybulgaria** [TypiCMS/Base#37]
We are facing the following error when trying to install the CMS with "composer create-project typicms/base typicms4":

SQLSTATE[42000] [1044] Access denied for user ''@'localhost' to database 'forge'

**Comment by sdebacker** [comment]
Yes, I'm debugging this weird problem.

**Comment by sdebacker** [comment]
Now It should work with Core 2.5.11. Just run composer update.
