### ISSUE TITLE
Disabling all "Online" languages throws error

### ISSUE THREAD

**Issue by chrismedina** [TypiCMS/Base#38]
Error 404
Sorry, this page was not found.
Go to our homepage?

I know someone would not likely do this but in the event they do they will have to manually get to the db to enable one of the languages to fix this error.

**Comment by sdebacker** [comment]
Thank you for the report, it's now fixed, but a breaking change occurred:
In app/Http/Kernel.php, move PublicLocale middleware from $middleware to $routeMiddleware array.
