### ISSUE TITLE
FatalErrorException in Container.php line 698: Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by jzfan** [TypiCMS/Base#42]
after   php artisan typicms:install , my  web http://localhost/cms/public/admin   get  error:
FatalErrorException in Container.php line 698:
Maximum function nesting level of '100' reached, aborting!

**Comment by sdebacker** [comment]
Please check this issue https://github.com/TypiCMS/TypiCMS/issues/39
