### ISSUE TITLE
angular & Material design integration? 

### ISSUE THREAD

**Issue by odyright** [TypiCMS/Base#46]
(how to use typicms with Angular material as frontend to have a beautiful design?

**Comment by sdebacker** [comment]
I think there are many ways of doing that, for example you can install it from npm, configure gulp, and remove bootstrap.

**Comment by odyright** [comment]
thanks @sdebacker, could you make me a demo/tutorial for it? i'm a beginner pls

**Comment by sdebacker** [comment]
Sorry, I don't have time and experience for that, but you will find a lot of doc on the web.
