### ISSUE TITLE
Cannot use Symfony\Component\HttpFoundation\File\UploadedFile

### ISSUE THREAD

**Issue by philmarc** [TypiCMS/Base#47]
I have a fresh install of TypiCMS, everything runs smoothly on local XAMPP.
This error appears when I try to upload a file (image) in the admin section for the Pages, New, Events, Slides, Categories, Projects.

I am talking about the single file upload form. The multiple upload form (dropzone js) for galleries works fine.

Here is the error :

```
FatalErrorException in RedirectResponse.php line 11:
Cannot use Symfony\Component\HttpFoundation\File\UploadedFile as UploadedFile because the name is already in use
```

The image is still uploaded and cropped though. Error seems to appear after the file manipulation.

Update : Tested online on my host, and everything works fine : no errors. It is probably due to a limitation of my local installation. You can close this issue.

**Comment by sdebacker** [comment]
Which version of Laravel is installed? Can you try to run composer update?
