### ISSUE TITLE
Documentation & Community

### ISSUE THREAD

**Issue by keevitaja** [TypiCMS/Base#48]
Hello,

Is there a better documentation available? I would like to try TypiCMS out, but i need some custom content types and page layouts.

**Comment by sdebacker** [comment]
Hello,

There is no better documentation as I have not enough time to write it. But if you know Laravel and some patterns like cache decorator, repository, presenter, you should be good to go.

**Comment by ilessy** [comment]
@keevitaja Or you can just use pyro, right? ^_^
But i will try this cms. It is a good way to learn how to write a laravel app.

**Comment by sdebacker** [comment]
When I begin to write TypiCMS, PyroCMS was a Code Igniter project without multilingual support.
