### ISSUE TITLE
Redirects to root directory

### ISSUE THREAD

**Issue by adnanafzal565test** [TypiCMS/Base#49]
I created a new module named "News" by executing command: composer require typicms/news. I also added providers in config/app.php, have publish views and migrations and migrated the database too. 

The only problem I am facing is that whenever the url I given, it redirects me to the root directory of my project, that is, http://localhost/mywebsite/public/

Even, if I give invalid route like http://localhost/mywebsite/public/foobar, instead of showing me error, it again redirects to the root directory.

I have checked the htaccess and routes.php file and there is no modifications.

Regards:
Adnan

**Comment by sdebacker** [comment]
Actually TypiCMS will not work correctly when installed in a subfolder; you should configure your apache vhost config to point to mywebsite/public directory.

**Comment by adnanafzal565test** [comment]
Okay. Thank you very much. I will try and let you know if that works.

**Comment by adnanafzal565test** [comment]
I hope creating vhost will work. But as I am using MAC, it is find painful to create vhost. So I end up uninstalling XAMPP and using MAMP. And it is working fine. 

Thank you for you time @sdebacker
