### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by othpiik** [TypiCMS/Base#54]
> SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) (View: /srv/www/dev11.local/resources/views/errors/404.blade.php)

just my first and fresh installation

**Comment by sdebacker** [comment]
You can manually correct .env file according to your database connexion settings.

**Comment by nikhil167** [comment]
Same problem here, even after the correction of .env file
 [PDOException]
 SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

**Comment by nikhil167** [comment]
I reseted my password and this happend after that >
[Symfony\Component\Debug\Exception\FatalErrorException] Cannot redeclare class CreatePermissionTables

Help

**Comment by sdebacker** [comment]
You have to delete one of the migration file. there are two CreatePermissionTables. in database/migrations

**Comment by nikhil167** [comment]
I got it .
Thanks

**Comment by sandeshsingh764** [comment]
SQLSTATE[HY000] [1045] Access denied for user 'purego6w@localhost'@'162.241.85.26' (using password: YES)

pls solve this
