### ISSUE TITLE
Pages & parent_id

### ISSUE THREAD

**Issue by mihy** [TypiCMS/Base#55]
Hi!

I cannot find if there is removed function to put page under other page as child or there is some issue?

And if it is new way, so how to make submenus?

**Comment by sdebacker** [comment]
You can do it with drag and drop in the list of pages.

**Comment by mihy** [comment]
I was like that. But today i just downloaded latest version - and it was not available. It is in menulinks, but not in pages. In pages you can only sort. And If I manually change parent_id from null to some id in DB, then with sorting (drag and drop) it will reset it to null.

**Comment by sdebacker** [comment]
Which version of typicms/base ?

**Comment by mihy** [comment]
"typicms/core": "~2.7.0"

**Comment by sdebacker** [comment]
Ok, I also have the problem. I will correct that ASAP.

**Comment by mihy** [comment]
Thx! I will be waiting! Nice work, btw

**Comment by sdebacker** [comment]
Done. You can do a composer update and It should be ok. Isn't it?

**Comment by mihy** [comment]
It will be not so easy. I have published Pages and Menu. But I will look at it and will inform :) Thx

**Comment by sdebacker** [comment]
Ok, there is just some changes in TypiCMS\Modules\Pages\Http\Controllers\AdminController

**Comment by mihy** [comment]
There should be changes in JS and some html? because there JS was not working to get putting under

**Comment by sdebacker** [comment]
You can get the content of listController.js and run ```gulp all```

**Comment by mihy** [comment]
Thanks a lot. I could not get it working on my yesterday project, but now I create new one, did update, gulp all and in new one it is working!
