### ISSUE TITLE
Large database table in admin

### ISSUE THREAD

**Issue by webfactorybulgaria** [TypiCMS/Base#56]
Hi Samuel,

We have a project with an admin module which has to manage thousands of records. I noticed that the API is serving the entire dataset and then the paging is done with angular. For small tables this is convenient but for large ones it takes forever to load. Have you thought about adding some limits in the database requests and using ajax for loading each page?

Nasko.

**Comment by sdebacker** [comment]
With 1000+ items, I create a custom optimized query, without eloquent. With more items, I would use server side pagination by reading doc of smart table : http://lorenzofox3.github.io/smart-table-website/

**Comment by Nolthar** [comment]
Where's that optimization ? i got similar problem and need these thing fast :/ for about 1100 news, list shows up after 8 - 14 seconds, and target number of news is about 5000 and more later. Where in components.min.js we can limit data taken to processing ? I though about preparing two lists - one full as normal and second really short, only for latest 50 news, where loading time is acceptable. But it's still only a workaround...

**Comment by sdebacker** [comment]
For now, you have to implement it by yourself in /resources/assets/typicms/components/list/ListController.js and regenerate components.min.js by running ```gulp all```. The next version of TypiCMS will include server side filtering and pagination of lists.
