### ISSUE TITLE
Page editing issue

### ISSUE THREAD

**Issue by ergonomicus** [TypiCMS/Base#57]
I can not edit page. When I press edit button editor opens, but there is no content in ckeditor, nor meta information...

If I add some content now and save the page - that new content will be displayed on front end, but when I come back to edit that page again, ckeditor is empty...

Any idea why is this happening?

**Comment by sdebacker** [comment]
Yes, it was a bug that should be already fixed. Does composer update fixes it ?

**Comment by ergonomicus** [comment]
@sdebacker Yes, that fixed it. I feel stupid now for not trying that first before posting the issue.

Thanks a lot!
