### ISSUE TITLE
Migration fails

### ISSUE THREAD

**Issue by neeilya** [TypiCMS/Base#59]
I have fresh TypiCMS/Base repo installed (composer install, created mysql 5.7 database).
When I run `php artisan migrate` I get this:

` [Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL  
  : alter table 'typicms_permission_user' add constraint 'permission_user_use  
  r_id_foreign' foreign key ('user_id') references 'typicms_users' ('id') on   
  delete cascade)`
  
  
` [PDOException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint`

**Comment by neeilya** [comment]
Sorry, looks like I misfollowed installation instructions.
However, I've gone through them and now I get

`ReflectionException in compiled.php line 1341:
Class TypiCMS\Modules\Core\Http\Middleware\SetLocale does not exist`

when I go to mywebsite.local

**Comment by sdebacker** [comment]
Master branch is in unstable state for now, you should install version 2.7.30 and not dev-master

**Comment by sdebacker** [comment]
I think the problem should be gone if you run ```composer update```
