### ISSUE TITLE
Class 'TypiCMS\Modules\Roles\Providers\ModuleProvider' not found

### ISSUE THREAD

**Issue by energeyes** [TypiCMS/Base#61]
Hi,
This error has been appear on `composer update` on Laravel 5.2:

`Class 'TypiCMS\Modules\Roles\Providers\ModuleProvider' not found
`

on command:
```
composer update
  - Removing typicms/core (2.7.31)
  - Installing typicms/core (2.7.32)
```

**Comment by sdebacker** [comment]
I just pushed v2.7.33, juste run composer update.

**Comment by energeyes** [comment]
Thanks!
It works
