### ISSUE TITLE
optimization auggestions

### ISSUE THREAD

**Issue by Nolthar** [TypiCMS/Base#62]
And what suggestions about optimization of queries ?

With the tableset of 10376 records I got query timings showed in attachment.(front side)

39 seconds is baaaaaddd.....

in the backend side i got 6 second for select all from typicms_news and 55 second fo select all from typicms_news_translations.

it's all about All() method from repositories

limiting to about 2500 records shorts timings, but it's not the point for frontend...

i though about:
1. in frontend homepage using cloned All() with limit to 50 last records - it's enough for blocks - maybe the best solution
2. Somehow force to query All() just once at the beginning and then take qhat i need in blocks
3. In backend i've added list without angular, just jquery, but it's still not enough, planning to make portions of records grouped by year of publication - feeding the list with data selected by year from date.

What' you can suggest also ?

Is it a way to optimize All() in any way ?

I've also done some VARCHAR-->CHAR tables optimization but with no significant results...

PS: Anyway - the module generator rocks and it's really helpful :)
![timings](https://cloud.githubusercontent.com/assets/10598280/15600991/be624bfe-23ed-11e6-9be3-573009d7d88c.JPG)

**Comment by sdebacker** [comment]
1. Try to do a left join in place of a ```where…in```.
2. Avoid to select all and select only the columns you need.

With these two optimisations, you will drastically lower the time needed for the query.

Also you have 3000+ queries, try to lower this number.

**Comment by sdebacker** [comment]
You can publish the module and work in the EloquentNews repository and the controllers to create a new method specifically for the backend.
