### ISSUE TITLE
ErrorException in News Module

### ISSUE THREAD

**Issue by gkouk** [TypiCMS/Base#66]
Hello,
firstly very good job! I have a fresh install of TypiCMS, everything runs smoothly on homestead. When I tried to install News module everything was OK in backend - the option News in menu has appeared, but in frontend I got the following error:
ErrorException in UrlGenerator.php line 307: Route [en.news.feed] not defined. (View: /home/vagrant/Code/typiCMS/resources/views/vendor/core/public/_feed-links.blade.php) (View: /home/vagrant/Code/typiCMS/resources/views/vendor/core/public/_feed-links.blade.php) (View: /home/vagrant/Code/typiCMS/resources/views/vendor/core/public/_feed-links.blade.php)
Could you please help me with this issue?
Thanks in advance,
George

**Comment by sdebacker** [comment]
Hello George, it should be ok now with TypiCMS/Core 2.8.6.

**Comment by gkouk** [comment]
Hello,
thanks for your quick response. I tried to install new Core and now I have another issue: when I run command 'php artisan typicms:install' for DB migration etc, I got the error:
[PDOException]
SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected
Regards,
George

**Comment by sdebacker** [comment]
Thanks for reporting, it's some sort of breaking change with laravel 5.2.33. I created TypiCMS/Base:2.8.7 with laravel fixed to 5.2.32 for now.

**Comment by sdebacker** [comment]
Ok, its now fixed

**Comment by gkouk** [comment]
Yes it's OK now. Thank you for your concern.
Regards,
George

**Comment by gkouk** [comment]
Hello again,
after the corrections you have made, I think that the following problem has occurred:
I install again the typiCMS and everything is OK except the backend environment. I could not view any page (admin/pages, admin/blocks, admin/Users, admin/Roles, etc.) they are blank pages without any error. I mention that there are records in the respective tables of database. Unless I have an issue on the local homestead.
Thanks in advance and sorry for the inconvenience,
George

**Comment by sdebacker** [comment]
Probably a JavaScript problem. All is working fine for me.

**Comment by gkouk** [comment]
OK I will search it, thank you!
