### ISSUE TITLE
Speed optimization suggestions

### ISSUE THREAD

**Issue by ixiixi** [TypiCMS/Base#68]
I made first website with TypiCMS and Laravel in general. Very impressed! The only problem is that i just can't get spee under 200ms for simple website, its always arround 300 - 450ms even with caching (0 queries) and after runing artisan optimize, route and config caching. Memcached is configured in app/config.php and running on server. For illustration here comes screeshot of debug bar: http://prntscr.com/bplw1b

Maybe i expect too much coming from Codeigniter older modified Pyrocms version, but i rarely had more than 150 ms. Maybe there are some tips and good practices optimizing TypiCMS speed? I would really appreciate some tips as some of my clients ask web project to pass Google PageSpeed tests and it requires speed to be under 200ms.

**Comment by sdebacker** [comment]
I made many websites with TypiCMS that passe Google PageSpeed tests without problems. If it's not the case, I can suggest you to use a server with PHP7.

**Comment by ixiixi** [comment]
Client server is originally on PHP 5.6, i tried to setup Cloudways/Digitalocean vps with PHP 7 for testing purposes and what a difference indeed! Now getting speeds arround 60-100ms which is quite nice. Thank you for the tip, should have thought about it myself!
