### ISSUE TITLE
Module not functional without slug field

### ISSUE THREAD

**Issue by faraz046** [TypiCMS/Base#70]
HI There!
While creating modules, i came across a situation where the slug field was in-applicable, and i have removed it from the migration and the model. 
But upon save i get undefined slug property error from the SlugObserver class. here is the specific code:

```
$slug = $model->slug ?: str_slug($model->title);
// slug = null if empty string
$model->slug = $slug ?: null;
```
So if the model does not have a slug field, it gives an error, And i cannot seem to find a way to override it, since the SlugObserver class is in the vendors folder.

There should be a way to create modules without slug field.

Cheers

**Comment by sdebacker** [comment]
Hello, just remote the observer from the ModuleProvider class.

**Comment by faraz046** [comment]
oh I overlooked that file.. Thanks it works great!
