### ISSUE TITLE
users without Superuser permission cannot login to admin

### ISSUE THREAD

**Issue by Nolthar** [TypiCMS/Base#71]
just receiving 403 permission denied.

I got some users witch permissions only for selected modules without superuser - and they cannot login...

What to do ?

**Comment by sdebacker** [comment]
Which url returns 403 ? If its /admin, just check **Access dashboard** in **User permissions**.

**Comment by Nolthar** [comment]
It's /admin.

Access dashboard is checked, user can enter after login at admin/dashboard and other modules, but not at admin/ alone.

It's explainable to user, but slightly unconvenient...


  ----- Original Message -----

**Comment by sdebacker** [comment]
Which version of TypiCMS do you have ? If you assign the administrator role, does it work ?

**Comment by Nolthar** [comment]
2.7, pure /admin route works only with superuser in my case.
  ----- Original Message -----

**Comment by sdebacker** [comment]
OK, the logic has changed in TypiCMS 2.8. You can upgrade to TypiCMS 2.8 or make a Pull Request to the TypiCMS 2.7 branch that solves the problem.
