### ISSUE TITLE
Adding fields to custom module

### ISSUE THREAD

**Issue by BKirev** [TypiCMS/Base#72]
I've created custom module, named Profiles(php artisan typicms:create profiles)
I'm trying to add more fields to it(like name, age, etc.). Did the migration, got the fields in DB, added them in the typicms\resources\views\vendor\profiles\admin\create.blade.php, as well in the $fillable in Profile model, but I'm getting this error:

`SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into`typicms_profiles`(`image`,`updated_at`,`created_at`) values (simple_image.jpg, 2016-07-20 14:22:05, 2016-07-20 14:22:05))`

A step-by-step tutorial for adding new custom module will be cool!

Good work on the CMS btw.

**Comment by sdebacker** [comment]
Hello, you did everything correctly, but by default MySQL is in strict mode. So you should add the name field in the form or add a default value for the name column, in your table.

**Comment by BKirev** [comment]
> So you should add the name field in the form

I thought I already did that? But yeah, last night I've added default(NULL) value to all newly created columns in DB and that solved the issue.
