### ISSUE TITLE
theme developing guide

### ISSUE THREAD

**Issue by moeinrahimi** [TypiCMS/Base#73]
hi i just started using typicms and i would like to make a theme for it,
since there is no complete docs about it i'm asking this here.
where is the default theme directory so i can customzie it upon my needs
and if there is any guide and tips i should know about theme developing i would be glad to hear it.

**Comment by ixiixi** [comment]
Hi, there is no dedicated theme folder. Views are located under /resources/views. JS and CSS files are located under /resources/js and /resources/css. Some js stuff like lightbox and swiper is under /public/js/public/master.js

**Comment by moeinrahimi** [comment]
@ixiixi thank you

**Comment by codivist** [comment]
@moeinrahimi did you ever have any success creating a theme for TypiCMS?
