### ISSUE TITLE
translate to another language

### ISSUE THREAD

**Issue by moeinrahimi** [TypiCMS/Base#74]
hi i would like to translate typicms to other language, what shoud i do ?

**Comment by rperello** [comment]
I'm doing traslation into **Spanish**, so i know something about it.

The are two kind of elements that need to be translated:

1. **lang files** inside some, not all, Modules of TypiCMS (Base, Blocks, Categories,...) that can be found at a folder, nicely named **lang** ;). Sometimes you can find this folder at this path '/src/resources/lang' or 'resources/lang'. You should duplicate one of the inner existing folders inside **lang** folder (I usually duplicate 'en' folder, rename it with the new language two-letter code and start traslating the inner files.

2. **Database Seeders** than you can find inside Module TypiCMS/Base at folder "/database/seeds", adding the news translated items (menus, pages,..).

What i recommend you is to create a new project

```
composer create-project typicms/base mywebsite
```
, make the above listed modifications and execute the installation (it's important this order as the installation executes the Database Seeders)

```
php artisan typicms:install
```

Before or after the **installation**, i doesn't matter, you should activate the new language adding the new language two-letter code to the 'locales' array variable at '/config/translateble.php'  of your TypiCMS installation.

After you check that all is working (at backoffice and frontend) and no errors are triggering when you are visiting url in the new language, you should fork the Modules that you have modified, apply the changes you made, and create one pull request per module modified indicating "Translation into ... ".

Keep in mind, that, with the default installation of TypiCMS, not all Modules are present. At least you should translate the Modules installed by default. Other Modules, as TypiCMS/News, are installed on demand, and will fallback to a default language (the one configured at /config/app.php) if they are not translated into the new language.

I hope this will guide you into the translation.
After reading again this explanation, seems a bit of work ;)
Thanks for your contribution.

Only for curiosity, what's the language you want to translate into?

Best Regards

**Comment by sdebacker** [comment]
@rperello Thank you for this good explanation!
