### ISSUE TITLE
Add custom module, 404 error page

### ISSUE THREAD

**Issue by likefilms** [TypiCMS/Base#75]
Hello! Added custom module Videos, created a new entry test.
When you try to see the writing on the front, getting a 404 error .
Tried so : http://vm23298.hv8.ru/en/videos/test
so:
http://vm23298.hv8.ru/en/test

Still I do not understand how to go to a page all records

Thank you!

**Comment by ixiixi** [comment]
Hi there, 
Did you add necessary line to /config/app.php ?
Did you associate page with new module (there is dropdown under Pages -> Edit -> Options -> module)?
 p.s. your provided links don't work

**Comment by likefilms** [comment]
Thank you! I did not do it:
"Did you associate page with new module (there is dropdown under Pages -> Edit -> Options -> module)?"
