### ISSUE TITLE
Projects url pattern not work, 404 error page.

### ISSUE THREAD

**Issue by raomingchao** [TypiCMS/Base#77]
Categories:
![image](https://cloud.githubusercontent.com/assets/7949453/17456096/56f25290-5bfe-11e6-8de8-63c35e68bbff.png)

Projects
![image](https://cloud.githubusercontent.com/assets/7949453/17456092/34823e1e-5bfe-11e6-918c-6fc7c3c8f265.png)

Link to the '/en/projects/contest/foo' 
![image](https://cloud.githubusercontent.com/assets/7949453/17456046/7973b1fc-5bfd-11e6-9b88-1e3e8f674a59.png)

**Comment by Lucas1314FN** [comment]
Any solution? Same problem here
