### ISSUE TITLE
Error after composer update

### ISSUE THREAD

**Issue by ixiixi** [TypiCMS/Base#78]
Hello,
I ran into error after composer update. 

Here is a screenshot of the error 
http://prntscr.com/c72rwh

I also tried to install fresh copy of typiCMS and after composer update it got the same error. 

Is it incompatibility with some updated package? I tried to run every clear artisan command like clear-compiled, cache:clear, config:clear, route:clear and view:clear hoping that maybe there are some old bits left in caches, but still same error.

**Comment by ixiixi** [comment]
No one else having this problem?

For those, who might be stuck with this, i solved it by downgrading laravel-translatable package to 5.6. Just run composer install dimsav/laravel-translatable 5.6

**Comment by sdebacker** [comment]
Yes it seems to be a new breaking change for a minor release… You have to fix laravel-translatable to 5.6.0, not 5.6.1.

**Comment by sdebacker** [comment]
I forced laravel-translatable to 5.6.0 in typicms/base 2.8.16.
