### ISSUE TITLE
An error occurred while deleting attachment.

### ISSUE THREAD

**Issue by likefilms** [TypiCMS/Base#79]
When you try to delete an image in a custom module, I receive an error "An error occurred while deleting attachment."

In the console error:
" 500 (Internal Server Error)"

Why it does not work api link : http://vm23298.hv8.ru/api/videos/2

Although http://vm23298.hv8.ru/api/videos/ works.

What is the problem?

**Comment by sdebacker** [comment]
I don't know exactly, your first link give me this error:

```
ErrorException in 341314ce3ccbb55477f4a2c1a16c18700559ed3b.php line 60:
Object of class Illuminate\Routing\Route could not be converted to string (View: /var/www/admin/data/www/vm23298.hv8.ru/resources/views/vendor/core/public/master.blade.php) (View: /var/www/admin/data/www/vm23298.hv8.ru/resources/views/vendor/core/public/master.blade.php)
```

The second link give me a login form.

**Comment by likefilms** [comment]
Try again go to the links and to log on to these data :

login: flywanderer@ya.ru
pass: testtest

Thank you!

**Comment by sdebacker** [comment]
http://vm23298.hv8.ru/api/videos/2 give me a 404 error.

**Comment by likefilms** [comment]
Yes. That is the problem.

**Comment by likefilms** [comment]
This link works :
http://vm23298.hv8.ru/api/videos

When you delete images in a custom module Videos is an appeal to http://vm23298.hv8.ru/api/videos/2 which returns a 404 error

You can go to the admin panel to check .

**Comment by sdebacker** [comment]
Did you solved the issue ? I just tried to delete an image in videos module and it worked.
