### ISSUE TITLE
Dropzone error?!

### ISSUE THREAD

**Issue by pdiveris** [TypiCMS/Base#82]
After doing a fresh installation I can't get image uploads to work. Dropzone seems to throw an error (see image attached). Please not that server write permissions etc are (as far as I can tell) correct.

![screen shot 2016-11-07 at 17 23 39](https://cloud.githubusercontent.com/assets/1022373/20067989/02d0a400-a50f-11e6-8899-4805cbddf625.png)

**Comment by sdebacker** [comment]
Thank you, I'll fix that ASAP.

**Comment by sdebacker** [comment]
Fixed in version 2.9.1. I replaced jQuery 3 by jQuery 2 because of the problem exposed here : https://github.com/enyo/dropzone/issues/1423
