### ISSUE TITLE
Gallery not showing?

### ISSUE THREAD

**Issue by pdiveris** [TypiCMS/Base#83]
Hi,

I am not sure this is actually an issue as such. I've created a gallery with a slug and a live status. If I visit the /x.y.com/gallery_url I get a 404. Is this how it should be? Or should the galley appear?

**Comment by pdiveris** [comment]
My bad, found it. Link galley to page. Apologies!

**Comment by sdebacker** [comment]
Yes that's the point.

**Comment by pdiveris** [comment]
But then why does it have a slug of its own? I am asking just out curiosity, no criticism intended!

**Comment by sdebacker** [comment]
So  you can access a single gallery at url /en/galleries/gallery-slug

**Comment by pdiveris** [comment]
Excellent. Thanks for the clarification, I wouldn't have guessed. Keep up the good work.

**Comment by pdiveris** [comment]
Although that doesn't seem to be working for me, with or without lang.
