### ISSUE TITLE
Cannot declare class CreatePermissionTables, because the name is already in use

### ISSUE THREAD

**Issue by nasirkhan** [TypiCMS/Base#84]
I just installed TypiCMS and tried to install the `News` module and got the following error. The `*_create_permission_tables` was created twice and that is why i got this error. i had to face same issue each time i run the command, 
```
php artisan vendor:publish
```

```
Cannot declare class CreatePermissionTables, because the name is already in use
```

**Comment by barnabas-szekeres** [comment]
Same issue here, after fresh install.

**Comment by ivarsmednis** [comment]
Hi, you'll probably find several create_permissions_tables files in /database/migrations folder. Make sure there is only one such file and delete duplicates.

**Comment by barnabas-szekeres** [comment]
Yes, exactly that was the problem, thanks @ivarsmednis! :)

Reproduction: Run twice the php artisan installer script. My first installation wasn't successfully so I run again and after that migration file also created again.

**Comment by calittle** [comment]
I know this issue is closed, but I also ran into it - somehow the database/migrations folder had been copied into the database/seeds folder, so it existed twice. Removing the extra copy in seeds resolved the problem.
