### ISSUE TITLE
Add new Language

### ISSUE THREAD

**Issue by martinklaus** [TypiCMS/Base#86]
Is possible to add new languages to the CMS?
Or only the three predefined working.
Why not a more flexible solution?

**Comment by sdebacker** [comment]
Yes it's possible by modifying the config/typicms.php file.

**Comment by barnabas-szekeres** [comment]
I think the right file is `config/translatable.php` instead of typicms.php

**Comment by sdebacker** [comment]
@barnabas-szekeres Yes you are right.
