### ISSUE TITLE
Thumbs is not appering with thumb name on galleries

### ISSUE THREAD

**Issue by AllanKlaus** [TypiCMS/Base#88]
I uploaded a image file, when I open the gallery the thumbs were not showing, but looking in source I saw the image there, the name was like this `/uploads/files/php-print1-370x370.png?token=215437d570118c1bdfa0257ebaff4a5b` so with inspector i changed this name to `/uploads/files/php-print1.png?token=215437d570118c1bdfa0257ebaff4a5b` and the image passed to appear, some can help with this?

**Comment by sdebacker** [comment]
I don't know exactly, you can check the croppa doc here : https://github.com/BKWLD/croppa/blob/master/README.md, especially the paragraph in Installation > nginx.
