### ISSUE TITLE
Compatibility issues between "components.min.js" and JS files from a personal template

### ISSUE THREAD

**Issue by michelew3design** [TypiCMS/Base#89]
I'd like to change the admin template with one downloaded from internet. I have replace the "admin.css" with my ".css" files but when i add my ".js" files, they have compatibility problems with jQuery/Angular in "components.min.js" and they does't work. 
How can i do? Alternately, is it possible to have the un-minified "components.js" file?

**Comment by ivarsmednis** [comment]
Yes, admin uses angular for listing modules. I don't think custom admin theme will work right out of the box.  The best option would be that you don't delete anything, but add your new theme gradually and check if it breaks after every step.

For components.js file. Please check gulpfile.js in root directory, there you can configure what goes in components file.

**Comment by michelew3design** [comment]
Perfect! Thanks a lot for your time :)
