### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by hossein-eud** [TypiCMS/Base#9]
Hi TypiCMS developer,

You have done a very very good work, congratulations and thank you very very much for publishing it open source.

I am trying to make a website for a friend who speaks German, English and French, so I tried to modify the code but no success at all. Maybe a milestone to add language management system would be a very good next step. 

I do a little work on lostideaslab.com, and I thought I may can do a little for TypiCMS, what do you think?

**Comment by sdebacker** [comment]
Thank you for your message, feel free to contribute to TypiCMS by making pull requests.

**Comment by hossein-eud** [comment]
The first part was a request for adding such Milestone to development process of TypiCMS, I am not a professional PHP programmer to code that myself. 

The second part is that I would like to work on how to get TypiCMS from a code piece on Github to a popular extension used by lots of people.
