### ISSUE TITLE
Set "updatepreferences" return Error 302

### ISSUE THREAD

**Issue by michelew3design** [TypiCMS/Base#90]
When i click in the toggle sidebar container a POST request is correctly sent to http://mydomani.local/admin/users/current/updatepreferences with the right parameters, but an error status code 302 is returned and the user preferences are not saved. Someone know why?

**Comment by sdebacker** [comment]
Are you logged as superuser or not ? If not, check in DB that the user have the permission "update-preferences"

**Comment by michelew3design** [comment]
Solved! Thanks man :)
