### ISSUE TITLE
Css is not loading after installation

### ISSUE THREAD

**Issue by nikhil167** [TypiCMS/Base#94]
I don't know for sure if it is an issue of css , But after installation my admin panel and website home page look like this > (i installed it in localhost using wamp)
![1](https://cloud.githubusercontent.com/assets/26650913/24576757/9d955390-16df-11e7-9811-12f7d0a28aa0.jpg)
![2](https://cloud.githubusercontent.com/assets/26650913/24576758/9d9b7c16-16df-11e7-8d95-a558ac76116d.jpg)

I'm a begginer help me.
Thanks

**Comment by nikhil167** [comment]
Hey,
Is There any online demo for this CMS?

**Comment by sdebacker** [comment]
There is no online demo. It seems that there is a problem with the font-awesome path.

**Comment by nikhil167** [comment]
Yea How i fix that
