### ISSUE TITLE
Categories in Menu as menulinks

### ISSUE THREAD

**Issue by mihy** [TypiCMS/Base#95]
There is issue with showing categories in menu. As I checked checkbox "Show categories" in menulink, there is showing error

Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Type error: Argument 1 passed to TypiCMS\Modules\Menus\Repositories\EloquentMenu::prepare() must be an instance of TypiCMS\NestableCollection or null, instance of Illuminate\Database\Eloquent\Collection given, called in /....../vendor/typicms/menus/src/Repositories/EloquentMenu.php on line 92 (View: /....../resources/views/vendor/menus/public/_menu.blade.php)

Trieded to change 
from:
$categories = $this->all();
to: (
$categories = $this->allNested();

in /....../vendor/typicms/categories/src/Repositories/EloquentCategory.php;
public function allForMenu($uri = '')
in line 41

and adding NestableTrait to /....../vendor/typicms/categories/src/Models/Category.php
and then I get errors like:

Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Type error: Argument 1 passed to TypiCMS\Modules\Menus\Repositories\EloquentMenu::setHref() must be an instance of TypiCMS\Modules\Menus\Models\Menulink, instance of TypiCMS\Modules\Categories\Models\Category given, called in /...../vendor/typicms/menus/src/Repositories/EloquentMenu.php on line 94 (View: /....../resources/views/vendor/menus/public/_menu.blade.php)

So is there any solution or I have to forget about to add categories in menu?

**Comment by sdebacker** [comment]
Hello,

This is fixed in Menus 2.9.2. Just run ```composer update```.
