### ISSUE TITLE
Set how many items in pagination

### ISSUE THREAD

**Issue by michelew3design** [TypiCMS/Base#96]
I'm trying to set the number of items for each page in the index route of a module, in admin area.
How can i set the number of items for the pagination?
I have create some new modules with `php artisan typicms:create mymodule` and i'd like to paginate its items (by default it's every 100 items).

Thanks, Michele

**Comment by sdebacker** [comment]
You can modify admin pagination in ListController.js, then run ```gulp all```

**Comment by michelew3design** [comment]
Ok perfect! Solved, thank you..
