### ISSUE TITLE
How to show index module inside the edit page of its related module?

### ISSUE THREAD

**Issue by michelew3design** [TypiCMS/Base#98]
I have a module related 1-n with an other model (something like Galleries-Files) and i'd like to show the list of the second one in the edit page (_form) of the first one (like in Galleries-Files).
How can i do this?

I have done the 2 modules with the relations and all works fine, but i don't know how can i do this angular modification.

Thanks, Michele

**Comment by sdebacker** [comment]
Angular is not required for this.

**Comment by michelew3design** [comment]
I have "Products" module and "Details" model.
The ration is 1 Product - n Details

I'd like to show the list of Details related to a single Product, inside the edit page of the Product, and Add/Edit/Delete the single Detail directly in that page.

So, in the Products/_form.blade i'd like to loop:
`<tr ng-repeat="model in displayedModels">` but `displayedModels` should be my `$product->details()` how can i do this? How can i loop the items of the relation inside the _form.blade of the model?

**Comment by sdebacker** [comment]
You have to learn by yourself how to do it with Angular/Laravel, and check the source code of galleries/files. I have too few time to write a complet explanation for that work, sorry.

**Comment by michelew3design** [comment]
Ok.. but i have to do this with Angular, write?
Probably with adding my directives in app.js and re-run the composer.min.js?

**Comment by sdebacker** [comment]
Yes you can do it with angular, and run "gulp all" to regenerate components.min.js.
You'll have to work in app.js and ListController.js.

**Comment by michelew3design** [comment]
Ok perfect, done! It works..
Thanks as usual!

**Comment by sdebacker** [comment]
Nice !
