### ISSUE TITLE
Multilingual galleries

### ISSUE THREAD

**Issue by aleksandar1909** [TypiCMS/Base#99]
Hi,

Is it possible to make a multilingual galleries?

Like when you're on page where is gallery "English" after choosing another language (e.g. Espanol) content changes including gallery to be "Espanol".

Thank you in advance.

**Comment by sdebacker** [comment]
Of course it is, which problem did you find?

**Comment by aleksandar1909** [comment]
The main issue is that I don't see the way I can make a gallery multilingual. I want the gallery that will change the pictures (files) depending on the selected language. So, is there any way I can do it? The main thing I want to achieve is when I switch tha language, pictures changes too. If that isn't possible, is it possible to switch between two galleries on language switch?

**Comment by sdebacker** [comment]
In this case I generally create 2 galleries, one is published only in first language and the other published for the other language.

**Comment by aleksandar1909** [comment]
Great, that's good to know.

Can you help me with it? How should I do it?

Thank you in advance.

**Comment by sdebacker** [comment]
Just change the status (green switch in the list)

**Comment by aleksandar1909** [comment]
I think we don't understand each other. :)

When I'm in Pages, there's a Galleries section, and I can choose only one gallery.

What I want is to add a gallery in another language that will be displayed instead of gallery that is in the primary language. So, if I have a gallery that contains picture that says "english", on language switch I need another gallery, with picture that says "espanol". 

Did I explain you now what problem do I have?

**Comment by sdebacker** [comment]
I understand you very well, no problem.
Normally in TypiCMS, it is possible to put multiple galleries on one page. I don't know why it is not the case at your side… Perhaps some screenshots could help.

**Comment by aleksandar1909** [comment]
Finally I succeded.

I had to add a field in database and rewrite _galleries.blade.php file by adding some conditions.

`@if ($gallery->type == "_home_slider" && $lang== 'sr')
        @include('galleries::public._slider', ['model' => $gallery])
    @elseif ($gallery->type == "_home_slider_en" && $lang=='en')
        @include('galleries::public._slider', ['model' => $gallery])
@endif`

My primary language is Serbian (`sr`) and the secondary is English (`en`).
